GravityPDF/gravity-pdf

- src/bootstrap.php
> Check for cURL functionality before enabling remote logging

- src/controller/Controller_Shortcodes.php
- src/model/Model_Shortcodes.php
- tests/unit-tests/test-shortcodes.php
> Add [gravitypdf] shortcode support for notifications

- src/helper/Helper_Options.php
- tests/unit-tests/test-options-api.php
Sanitize Custom Paper Size values so no negative numbers can be included (they'll automatically get converted to positive numbers)
Fixed #23
> Fix Negative Paper Size Bug

- src/helper/Helper_Options_Fields.php
Change the "Default Font Type" label to "Default Font" which is more accurate.
> Change default font label

- src/assets/js/gfpdf-settings.js
> Duplicating PDFs don't update shortcode preview ID

- src/assets/js/gfpdf-settings.js
> Fix AJAX Notice when navigating away from page

- src/controller/Controller_Install.php
- src/views/View_Settings.php
> Fixes WP_MEMORY_LIMIT and WP_MAX_MEMORY_LIMIT conflict

- src/helper/Helper_Migration.php
- tests/phpunit/unit-tests/test-actions.php
- tests/phpunit/unit-tests/test-migration.php
> Cleanup the 'output' directory during the v3 to v4 migration

- README.md
- composer.json
- composer.lock
- Remove the NPM trickiness used in our composer file and update our README.md file to reflect this new change
> Simplify Composer

- src/helper/Helper_Misc.php
Bug: Fix issue with our tmp file we use to test for writability not being found (even though we have checks in place to prevent this)
> Fix file writing edge case

- src/helper/Helper_Form.php
- Resolve problem introduced when we bypassed the GFAPI for performance reasons
Fixes #61
> Fix Gravity Forms Inactive Bug when adding/editing/deleting PDFs

- src/views/html/PDF/entry_list_pdf_single.php
Fixes PDF view issue in Commit #862385bfa35ecc67d9073228145f3fa0b651c2a7
> Fixes unintended notice introduced in earlier commit 

- initialisation/templates/config/zadani.php
- src/helper/Helper_Options_Fields.php
- src/model/Model_Form_Settings.php
- src/views/html/PDF/core_template_styles.php
- tests/phpunit/unit-tests/test-form-settings.php
- tests/phpunit/unit-tests/test-pdf.php
> Change the 'background' field key to 'background_image'

- initialisation/templates/config/zadani.php
- src/helper/Helper_Options_Fields.php
- src/model/Model_Form_Settings.php
- src/views/html/PDF/core_template_styles.php
- tests/phpunit/unit-tests/test-form-settings.php
- tests/phpunit/unit-tests/test-pdf.php
> Add core `background_color` field to zadani

- initialisation/templates/config/zadani.php
- initialisation/templates/zadani.php
- src/helper/Helper_Options_Fields.php
- src/model/Model_Form_Settings.php
- src/views/View_PDF.php
- tests/phpunit/unit-tests/test-form-settings.php
While writing the documentation there was confusion about what this particular option did. This patch fixes that problem and makes it explicitly clear what it does.
Fixes #69
> Change 'show_hidden' template field to 'enable_conditional' 

- src/helper/Helper_Options_Fields.php
> Remove question marks from all our field names

- api.php
- tests/phpunit/unit-tests/test-api.php
> Add Helper_Forms getter class to our GFPDFAPI class

- src/controller/Controller_Actions.php
- src/controller/Controller_Form_Settings.php
- src/controller/Controller_Install.php
- src/controller/Controller_PDF.php
- src/controller/Controller_Settings.php
- src/controller/Controller_Shortcodes.php
- src/controller/Controller_Welcome_Screen.php
- src/model/Model_Actions.php
- src/model/Model_Form_Settings.php
- src/model/Model_Install.php
- src/model/Model_PDF.php
- src/model/Model_Settings.php
- src/model/Model_Shortcodes.php
- src/model/Model_Welcome_Screen.php
- src/views/View_PDF.php
- src/views/View_Settings.php
- src/views/View_Welcome_Screen.php
When we began injecting our depedancies into our MVC classes we rushed it and didn't include appropriate DOCBLOCKs. This resolves that issue.
Fixes #78
> Add missing DOCBLOCK for our MVC __constructs

- api.php
- src/helper/Helper_PDF.php
- src/model/Model_PDF.php
- tests/phpunit/unit-tests/test-slow-pdf-processes.php
Still need to add similar functionality to the GFPDFAPI and add unit testing before merge.
Once finalised, it will resolve #44
> More easily generate PDFs via single method in Model_PDF

- src/views/html/Actions/migration.php
> Fix typo found in the migration message

- src/depreciated.php
- src/views/View_PDF.php
- tests/phpunit/unit-tests/test-pdf.php
> Fix string returning problem with depreciated HTML output functions

- src/helper/Helper_Misc.php
- src/helper/fields/Field_List.php
- src/helper/fields/Field_Products.php
- src/views/html/PDF/core_template_styles.php
- tests/phpunit/unit-tests/test-helper-misc.php
- Move Product and List field styles our of their associated helper classes and place them in our core template style loader (which contains our header/footer and background code).
- Change the background and border colours to match the dynamic background colour being used using hex colour manipulation
Resolves #58
> Optimise List and Product Styles

- src/assets/js/gfpdf-settings.js
- src/helper/Helper_Data.php
> Add a default message when the last PDF is removed from the list

- src/assets/css/gfpdf-styles.css
- src/assets/js/gfpdf-settings.js
> Add a loading spinner to our duplicate and delete AJAX actions

- src/model/Model_Install.php
- tests/phpunit/unit-tests/test-installer.php
> Allow explicit control over where Gravity PDF stores its filesystem using filters

- src/helper/abstract/Helper_Abstract_View.php
- src/views/View_Actions.php
- src/views/View_Form_Settings.php
- src/views/View_PDF.php
- src/views/View_Settings.php
- src/views/View_Shortcodes.php
- src/views/View_Welcome_Screen.php
> Standardise the $ViewType naming convention

- src/helper/abstract/Helper_Abstract_View.php
- src/views/html/PDF/core_template_styles.php
- src/views/html/Settings/tools.php
- src/views/html/Welcome/update.php
- src/views/html/Welcome/welcome.php
> Passing in the $gfpdf object to our HTML views automatically

- src/helper/fields/Field_Creditcard.php
> Add support for the Credit Card field

- .travis.yml
- pdf.php
> Bump our WP minimum requirement

- src/helper/Helper_Options_Fields.php
> Change our default font size to 10pt

- src/bootstrap.php
- src/controller/Controller_Form_Settings.php
- src/controller/Controller_Welcome_Screen.php
- src/helper/Helper_Data.php
- src/helper/Helper_Migration.php
- src/helper/Helper_Options_Fields.php
- src/helper/Helper_PDF_List_Table.php
- src/helper/abstract/Helper_Abstract_Options.php
- src/helper/interface/Helper_Interface_Config.php
- src/model/Model_Actions.php
- src/model/Model_Form_Settings.php
- src/model/Model_PDF.php
- src/model/Model_Settings.php
- src/model/Model_Shortcodes.php
- src/templates/config/legacy.php
- src/templates/config/zadani.php
- src/views/View_PDF.php
- src/views/View_Settings.php
- tests/phpunit/unit-tests/test-autoloader.php
> Make Helper_Options an abstract class

- src/helper/Helper_PDF.php
- src/helper/abstract/Helper_Abstract_Options.php
- src/helper/fields/Field_Products.php
- src/helper/fields/Field_Signature.php
- src/model/Model_Install.php
- src/model/Model_PDF.php
Also standardise to single quotes in actions and filters
Fixes #20
> Remove any filters from within other filters

- api.php
- tests/phpunit/unit-tests/test-api.php
> Add Singleton class functionality to our api

- pdf.php
> Add Gravity Forms link to minimum requirements message

- src/bootstrap.php
- src/controller/Controller_Install.php
- src/helper/Helper_Data.php
- src/helper/Helper_Options_Fields.php
- src/helper/Helper_PDF.php
- src/helper/abstract/Helper_Abstract_Options.php
- src/model/Model_Install.php
- src/view/html/Settings/system_status.php
> Refine Gravity PDF copy

- composer.json
> Fix regression after changing view directory name from "views" to "view"

- src/helper/Helper_PDF.php
Also pass Helper_PDF object to the 4.0 filters
Fixes #138
> Include our full-page display mode in our init() function 

- src/model/Model_PDF.php
- src/model/Model_Shortcodes.php
- src/view/View_PDF.php
- tests/phpunit/unit-tests/test-pdf.php
- tests/phpunit/unit-tests/test-shortcodes.php
> Add ability to show print dialog using [gravitypdf] shortcode

- src/helper/Helper_Field_Container.php
- src/helper/fields/Field_Products.php
- src/view/View_PDF.php
- src/view/html/PDF/core_template_styles.php
- tests/phpunit/unit-tests/test-field-container.php
- tests/phpunit/unit-tests/test-pdf.php
This allows manipulation of the generated HTML in mPDF
> Tweak the HTML output to be better formatted 

- src/assets/css/gfpdf-styles.css
> Fix minor RTL issues in our UI when CSS sets "direction: rtl"

- src/helper/Helper_Misc.php
- src/view/View_PDF.php
- tests/phpunit/unit-tests/test-pdf.php
> Fix image max-height issue in header and footer

- src/helper/Helper_Misc.php
- src/helper/Helper_Options_Fields.php
- tests/phpunit/unit-tests/test-helper-misc.php
Also updated Header description to reflect the changes.
Fixes #168
> Allow images to be correctly left, center and right-aligned in header/footer

- src/controller/Controller_PDF.php
- src/helper/Helper_PDF.php
- src/view/View_PDF.php
Note: shortcodes are NOT processed in the header or footer by default
Fixes #171
> Correctly convert mergetags in the header and footer.

- src/helper/Helper_Misc.php
- src/helper/fields/Field_Quiz.php
- tests/phpunit/unit-tests/test-helper-misc.php
It produces more consistent results
Fixes #172
> Swap to the innerHTML5 method when using the QueryPath library

- src/templates/blank-slate.php
- src/templates/focus-gravity.php
- src/templates/rubix.php
- src/templates/zadani.php
- src/view/html/PDF/core_template_styles.php
> Place default table CSS in the core template file

- pdf.php
- src/helper/Helper_Options_Fields.php
- src/view/html/Welcome/update.php
- src/view/html/Welcome/welcome.php
See https://github.com/GravityPDF/gravity-pdf/issues/113#issuecomment-167715039 for details on why we decided on 4 templates instead of 5.
> Change copy from "five" free templates to "four"

- src/helper/Helper_Options_Fields.php
> Ensure default PDF template is Zadani

- src/templates/blank-slate.php
- src/templates/focus-gravity.php
> Remove camel case from our PDF templates

- src/helper/Helper_Misc.php
- src/model/Model_Form_Settings.php
- src/templates/config/blank-slate.php
- src/templates/config/focus-gravity.php
- src/templates/config/legacy.php
- src/templates/config/rubix.php
- src/templates/config/zadani.php
- tests/phpunit/unit-tests/test-form-settings.php
- tests/phpunit/unit-tests/test-helper-misc.php
> Make our Template Configuration classes use sentence case 

- src/templates/rubix.php
> Remove background colour from our list and product th elements

- src/helper/abstract/Helper_Abstract_Options.php
> Include Free Sans/Free Serif/Free Mono fonts in our unicode list

- src/controller/Controller_PDF.php
- src/model/Model_Install.php
- src/model/Model_PDF.php
- tests/phpunit/unit-tests/test-pdf.php
Moved fontdata from `tmp` directory to prevent confict when tmp directory gets cleaned up. Now located in `/PDF_EXTENDED_TEMPLATES/fonts/fontdata/`
This should resolve #156
> Change the fontdata folder

- src/helper/Helper_Options_Fields.php
> Tweak the owner restriction label for better UX

- src/helper/Helper_Misc.php
- src/templates/rubix.php
- src/view/html/PDF/core_template_styles.php
- tests/phpunit/unit-tests/test-helper-misc.php
This is done by consolidating the colour calculation code into Helper_Misc (previously in core_template_styles.php). We updated core_template_styles.php to take advantage of the new method.
Fixes #199.
> Resolved the Rubix background/border issue

- src/helper/fields/Field_Products.php
This is to be consistent with our list tables. See https://github.com/GravityPDF/gravity-pdf/pull/204
> Add <tbody> with class name to product table head and contents

- src/helper/fields/Field_Products.php
- src/templates/zadani.php
To do this we added to new class names to our products table.
Fixes #200
> Move the order title closer to the table in Zadani

- src/templates/focus-gravity.php
> Fix up some style conflicts in Focus Gravity

- src/helper/Helper_Migration.php
> Add font migration for multisite

- src/helper/fields/Field_Fileupload.php
> Add better checks for our File Upload field helper class

- src/model/Model_PDF.php
> Check for existing of the advanced template key before looking at its value

- src/model/Model_PDF.php
> Prevent notice by checking our 'save' array key exists before checking its value

- src/helper/Helper_Misc.php
- src/templates/blank-slate.php
- src/templates/focus-gravity.php
- src/templates/rubix.php
- src/templates/zadani.php
- tests/phpunit/unit-tests/test-helper-misc.php
> Include $field variable in PDF templates

- src/model/Model_PDF.php
> Move the save actions to our generate_and_save_pdf() method.

- api.php
Also mark class as "final" for a couple of versions until it stabalises.
> Use late static binding in our API.

- src/helper/fields/Field_Default.php
- src/helper/fields/Field_Multiselect.php
- src/helper/fields/Field_Poll.php
- src/helper/fields/Field_Post_Category.php
- src/helper/fields/Field_Post_Content.php
- src/helper/fields/Field_Section.php
- src/helper/fields/Field_Survey.php
- src/model/Model_PDF.php
Also make the Field code more uniform and add missing Field Post_Content class.
This helps resolve #240 with the help of a patch file I submitted to the plugin author.
> Modify Field filters for greater 3rd-party customisation

- src/assets/js/gfpdf-settings.js
- src/helper/Helper_Options_Fields.php
- src/helper/abstract/Helper_Abstract_Options.php
- src/model/Model_Form_Settings.php
- src/view/View_PDF.php
- tests/phpunit/unit-tests/test-form-settings.php
- tests/phpunit/unit-tests/test-options-api.php
- Prevent core font, size and colour styles loading in v3 templates
- Add appropriate unit tests for our new methods
Resolves #246
> Show/Hide the front-end font, size and colour fields when using v3 template

- src/view/View_PDF.php
Also prevent future issues with captcha or password fields.
Fixes #264
> Fix issue with empty page field showing up on PDF

- src/helper/abstract/Helper_Abstract_Options.php
> Check for both form ID and PDF ID before trying to get settings

- src/helper/abstract/Helper_Abstract_Options.php
Correct load multisite templates and then any in the root directory structure. This allows a single PDF template to be applied to multiple multisite installs.
Remove the "User Template" prefix from the list.
> User Template Refinements

- src/controller/Controller_Shortcodes.php
- src/model/Model_Shortcodes.php
- src/view/html/Shortcodes/gravitypdf.php
> Change shortcode 'classes' to 'class' but leave in backwards compat support

- src/helper/Helper_PDF.php
Include the Gravity Form in the 'gfpdf_mpdf_init_class' filter too.
> Include $form in our gfpdf_mpdf_class filter

- src/helper/abstract/Helper_Abstract_Options.php
- Cleanup comments
- Tweak filters
- Rename variables for better readability
> Housekeeping on Helper_Abstract_Options (variable rename / comment tweak)

- src/controller/Controller_Settings.php
- src/view/html/Settings/general.php
- src/view/html/Settings/help.php
- src/view/html/Settings/tools.php
- tests/phpunit/unit-tests/test-settings.php
Ensure the uninstaller is included on the tools page.
Fix up unit tests
> Rename the hooks on the settings tabs to be more descriptive

- src/depreciated.php
- src/helper/abstract/Helper_Abstract_Fields.php
Tidy up the html() method, focusing on the 'gfpdf_field_html_value' filter.
> Housekeeping for Helper_Abstract_Fields

- api.php
- Fix up comments in the API
- Modify logging comment and fix up our likert returns.
> Housekeeping for API

- src/helper/fields/Field_Product.php
- tests/phpunit/unit-tests/test-form-data.php
> Ensure the product option fields in the form data array are accurate

- src/helper/Helper_Misc.php
- src/model/Model_Install.php
> Use WP in-built function to check if the folder is writable.

- src/view/html/PDF/core_template_styles.php
> Force text to wrap inside table cells to prevent text resizing

- src/helper/Helper_Migration.php
> Remove the font's config.php file during a migration.

- src/helper/Helper_Data.php
- src/model/Model_Install.php
> Include our overloaded data properties so IDEs will match them correctly

- src/bootstrap.php
- src/controller/Controller_Actions.php
- src/controller/Controller_PDF.php
- src/helper/Helper_Migration.php
- src/helper/Helper_Misc.php
- src/helper/abstract/Helper_Abstract_Options.php
- src/model/Model_Form_Settings.php
- src/model/Model_Install.php
- src/model/Model_PDF.php
- src/model/Model_Settings.php
- src/model/Model_Shortcodes.php
- src/view/View_PDF.php
- src/view/View_Settings.php
- Reduce the size of the information included in the logs
Fixes #319
> Standardise the additional logging information passed

- src/view/html/Actions/review_plugin.php
> Tweak the plugin review message

- api.php
- pdf.php
- src/bootstrap.php
- src/controller/Controller_Actions.php
- src/controller/Controller_Install.php
- src/controller/Controller_Settings.php
- src/helper/Helper_Data.php
- src/helper/Helper_Misc.php
- src/helper/Helper_Options_Fields.php
- src/helper/Helper_PDF.php
- src/helper/Helper_PDF_List_Table.php
- src/helper/abstract/Helper_Abstract_Fields.php
- src/helper/abstract/Helper_Abstract_Options.php
- src/helper/fields/Field_Poll.php
- src/helper/fields/Field_Post_Category.php
- src/helper/fields/Field_Post_Custom_Field.php
- src/helper/fields/Field_Signature.php
- src/helper/fields/Field_Survey.php
- src/model/Model_Form_Settings.php
- src/model/Model_Install.php
- src/model/Model_PDF.php
- src/model/Model_Shortcodes.php
- src/view/html/PDF/core_template_styles.php
- src/view/html/Settings/general.php
- src/view/html/Settings/help.php
- src/view/html/Settings/system_status.php
- src/view/html/Settings/tools.php
- src/view/html/Welcome/more.php
- src/view/html/Welcome/update.php
- src/view/html/Welcome/welcome.php
This includes public links for the user, as well as direct links to actions/filter/api documentation
Partially resolves #14 but the links included point to our staging environment at the moment. Still have to convert to our production URLs before releasing this to the public
> Integrate website links into plugin

- src/helper/fields/Field_Likert.php
- src/helper/fields/Field_Rank.php
- src/helper/fields/Field_Rating.php
- tests/phpunit/unit-tests/test-api.php
Calling the correct order of operations to get the correct HTML value for the Likert, Rank and Rating survey fields
Also tested the polls, quiz and signature add-ons for compatibility issues.
Resolves #327
> Fix up Survey 3.0 issues

- src/helper/fields/Field_Tos.php
- src/templates/blank-slate.php
- src/templates/focus-gravity.php
- src/templates/rubix.php
- src/templates/zadani.php
> Add Terms of Service (Gravity Perk) Support

- src/helper/Helper_Misc.php
- src/model/Model_PDF.php
> Ensure Gravity Forms GFEntryDetail class loaded prior to PDF generation

- src/helper/Helper_Misc.php
- tests/phpunit/unit-tests/test-helper-misc.php
> Convert referenced images in headers or footers to paths when found on the local server

- src/helper/Helper_PDF.php
Also included $this->form as protected property in class
Resolves #358
> Ensure password and master password have mergetags processed

- src/helper/Helper_Data.php
- src/model/Model_Install.php
- src/model/Model_PDF.php
- src/model/Model_Settings.php
- tests/phpunit/unit-tests/test-installer.php
> Store fontdata path in Helper_Data class using `template_fontdata_location`

- src/controller/Controller_Activation.php
> Check Gravity PDF actually loaded before trying to run deactivation

- src/templates/config/blank-slate.php
- src/templates/config/focus-gravity.php
- src/templates/config/rubix.php
> Fix up name config errors

- src/helper/abstract/Helper_Abstract_Options.php
> Disable default sanitation when using Helper_Abstract_Options::settings_sanitize()

- src/view/html/PDF/entry_detailed_pdf.php
- src/view/html/PDF/entry_list_pdf_multiple.php
- src/view/html/PDF/entry_list_pdf_single.php
> Don't open new window when downloading PDF

- src/view/html/Shortcodes/gravitypdf.php
> Open PDF Link in new Window when using [gravitypdf] shortcode with 'view' attribute

- src/controller/Controller_Shortcodes.php
- src/model/Model_Shortcodes.php
- Check for the [gravitypdf] shortcode when using the GravityView Custom Content field and add the entry ID to it automatically
- Refractor the code that does the search and replace for the [gravitypdf] shortcode so it's easily callable.
Resolves #405
> Add basic GravityView Support

- src/view/html/PDF/entry_detailed_pdf.php
> Ensure View/Download links are on a new line in Entry Details page

- src/depreciated.php
- tests/phpunit/unit-tests/test-slow-pdf-processes.php
> Add backwards compat support for GFPDF_Core_Model::gfpdfe_save_pdf()

- gulpfile.js
- package.json
- pdf.php
- src/assets/languages/README.MD
- src/assets/languages/gravity-forms-pdf-extended.pot
- src/bootstrap.php
- src/view/html/Welcome/update.php
- Add automated tooling to generate POT file and include in repo
- Add README into languages folder for users using translation files
- Move load_plugin_textdomain() into its own function
> Finalise Translation Support

- src/helper/fields/Field_Post_Category.php
> Fix PHP Array to String conversion error when no category selected

- src/helper/Helper_Migration.php
- src/helper/abstract/Helper_Abstract_Options.php
- src/model/Model_PDF.php
> Fix glob() error when it returns `false`

- src/bootstrap.php
- Add support for version 1.1 of GF Logger
- Ensure Monolog is disabled when not running GF logging
This may fix #428
> Update our GF Logging integration

- src/model/Model_PDF.php
> Check if the pagination key exists before trying to use it

- api.php
- src/helper/fields/Field_Products.php
- src/model/Model_PDF.php
- src/view/View_PDF.php
Fixes notice when calling GPDFAPI::product_table() and tidies up our HTML generation code
Resolves #438
> Add an is_empty() call to our Field_Products class and start using

- src/controller/Controller_PDF.php
- src/model/Model_PDF.php
- tests/phpunit/unit-tests/test-pdf.php
> Cleanup PDF from disk after entry is edited

- src/templates/blank-slate.php
- src/templates/focus-gravity.php
- src/templates/rubix.php
- src/templates/zadani.php
- src/view/html/PDF/core_template_styles.php
- tests/phpunit/unit-tests/test-options-api.php
> Remove arbitrary font sizes and remove cascade usage in core template styles

- src/helper/Helper_Options_Fields.php
> Refine the Show Page Names description

- src/helper/fields/Field_Name.php
> Fix up PHP notice for legacy GF users

- src/helper/Helper_Misc.php
> Allow files to be overridden when using copyr()

- src/helper/Helper_PDF.php
> Set master password to null so it's automatically generated by mpdf

- src/assets/js/gfpdf-backbone.js
> Ensure _.template() functions the same when using Underscore 1.6 or 1.8

- src/helper/fields/Field_Checkbox.php
- src/helper/fields/Field_Radio.php
Resolves #415 which previously only fixed html()
> Apply HTML decoding in value() so html() and form_data() both take advantage

- src/bootstrap.php
- tests/phpunit/unit-tests/test-bootstrap.php
> Queue admin assests during admin_enqueue_scripts action

- src/model/Model_Actions.php
- src/model/Model_Install.php
> Fix up depreciation noticed in WP 4.6 when using wp_get_sites()

- src/model/Model_PDF.php
> Add support for "almost pretty" permalinks which has index.php in the URL when viewing PDFs

- src/helper/fields/Field_Textarea.php
> Apply wpautop() to Rich Text Paragraph field

- src/view/View_PDF.php
> Only show the product table if we aren't showing individual products in the template

- src/helper/Helper_Misc.php
- src/model/Model_PDF.php
- tests/phpunit/unit-tests/test-helper-misc.php
> Process merge tags in the password field for our legacy Tier 2 PDF Templates

- src/model/Model_Install.php
> Correctly register our almost pretty PDF permalink

- src/helper/Helper_PDF.php
- src/model/Model_PDF.php
This patch is apart of the fix for #492
> Ensure Header/Footers merge tags are processed before running wp_kses_post()

- src/model/Model_Actions.php
- tests/phpunit/unit-tests/test-actions.php
> Prevent review notice showing up on non-Gravity Forms pages

- src/assets/js/react/components/TemplateDeleteButton.js
- src/assets/js/react/components/TemplateFooterActions.js
- src/assets/js/react/components/TemplateHeaderNavigation.js
- src/assets/js/react/components/TemplateList.js
- src/assets/js/react/components/TemplateListItem.js
- src/assets/js/react/components/TemplateListItemComponents.js
- src/assets/js/react/components/TemplateSingle.js
- src/assets/js/react/components/TemplateSingleComponents.js
- src/assets/js/react/router/templateRouter.js
- src/assets/js/react/selectors/getTemplates.js
- src/helper/Helper_Data.php
- tests/mocha/unit-tests/components/template.header.navigation.spec.js
- tests/mocha/unit-tests/components/template.list.item.components.spec.js
- tests/mocha/unit-tests/components/template.single.components.spec.js
* Fix default callback issue when deleting templates
* Move missing JS text to PHP so they can be translated
> Advanced template selector bug fixes

- src/assets/css/gfpdf-styles.css
Usage: `'class'   => 'image-radio-buttons'`
> Add support for Radio button images in custom radio fields

- api.php
- src/model/Model_Settings.php
- tests/phpunit/unit-tests/test-api.php
This will allow users to programmatically add custom fonts to Gravity PDF.
> Added Font Create and Delete endpoints to GPDFAPI

- src/assets/js/gfpdf-settings.js
This fixes a problem with us reinitialising the gfMergeTags() class when a new template is loaded
> When dynamically loading template fields we'll reset gfMergeTags.getTargetElement

- tests/bin/install.sh
- tests/phpunit/unit-tests/test-ajax.php
- Include the test data
- Reset the DB connection for AJAX tests
> Fix PHP errors during latest unit tests

- .travis.yml
Remove 7.1 from the allow failure list for Travis.
> Updates made to Mpdf to become PHP7.1 compatible

- src/bootstrap.php
Also remove chosen CSS which isn't required anymore.
> Ensure the jQuery UI Dialog CSS is included with our GPDF styles

- src/bootstrap.php
- Ensure Gravity Forms chosen JS is a dependency when loading our JS
- Ensure chosen CSS is whitelisted in GF No-Conflict Mode
> Fix regressions switching to Gravity Forms Chosen JS package

- src/assets/js/react/components/TemplateUploader.js
- src/model/Model_Templates.php
- Fix up generic template error JS bug
- Include template upload limit to 10MB
> Advanced template error fixes

- src/assets/js/gfpdf-settings.js
> Ensure the PDF Delete dialog will show up after being canceled

- src/assets/css/gfpdf-styles.css
- src/assets/js/react/components/TemplateList.js
- src/assets/js/react/components/TemplateUploader.js
- src/assets/js/react/router/templateRouter.js
- src/helper/Helper_Data.php
This includes what file type we expect to be uploaded and also includes a warning about overriding existing PDF templates.
Resolves #578
> Add PDF Template Installation helper text

- src/controller/Controller_PDF.php
- src/helper/fields/Field_Multiselect.php
- src/model/Model_PDF.php
- tests/phpunit/bootstrap.php
- tests/phpunit/unit-tests/test-form-settings.php
- tests/phpunit/unit-tests/test-gravity-forms.php
Add full support for the changes present in Gravity Forms 2.2 Beta 2
> Gravity forms 2.2 support

- src/controller/Controller_Welcome_Screen.php
- tests/phpunit/unit-tests/test-welcome-screen.php
> Prevent redirect if headers already sent

- src/helper/Helper_Templates.php
> Change error to warning when we cannot load template config

- src/helper/Helper_Field_Container.php
- src/model/Model_PDF.php
> Add additional filters during PDF generation to change functionality

- src/assets/js/gfpdf-settings.js
- src/helper/Helper_Options_Fields.php
- src/helper/abstract/Helper_Abstract_Options.php
Also add option to enable the master password in the UI (not recommended)
Resolves #617
> Fix master password issue in v3 to v4 migration

- .travis.yml
- pdf.php
- src/model/Model_Shortcodes.php
Filter shortcode regex to the shortcode we are looking for using WordPress 4.4 functionality (bump min version).
Resolves #626
> Fix [gravitypdf] error in GravityView

- src/helper/Helper_Templates.php
This will allow devs to pick and choose which class they implement
Fixes #629
> Remove restriction on Helper_Interface_Config for the template config class

- src/helper/abstract/Helper_Abstract_Fields.php
Since the end user has no control over the contents of administrative fields we'll allow them to be processed in the PDF.
Resolves #615
> Allow merge tags/shortcodes to display in PDF for administrative fields

- src/helper/Helper_Field_Container.php
- src/view/html/PDF/core_template_styles.php
- tests/phpunit/unit-tests/test-field-container.php
> Add support for 'pagebreak' CSS class name to force a new page after the field

- src/controller/Controller_PDF.php
- src/model/Model_PDF.php
- src/view/View_PDF.php
- tests/phpunit/unit-tests/test-pdf.php
> Add middleware to determine if fields should be skipped in core markup

- gulpfile.js
- src/assets/css/gfpdf-admin-styles.css
- src/assets/css/gfpdf-styles.css
- Ensure translation is only done on the Gravity PDF files
- Fix up relative image path issue with /dist/ directory
> Optimise gulp build

- src/controller/Controller_PDF.php
- src/model/Model_PDF.php
> Add our registered query vars as ignored params when Gravity View renders view on front page

- src/helper/fields/Field_Product.php
> Don't show the selected options in the product field when individual products are enabled

- src/bootstrap.php
- src/controller/Controller_Form_Settings.php
- tests/phpunit/unit-tests/test-form-settings.php
Resolves https://github.com/GravityPDF/gravity-pdf/issues/640
> Fix edge case PDF setting conflict when form is updated

- src/assets/js/gfpdf-backbone.js
- src/assets/js/gfpdf-settings.js
- src/helper/Helper_PDF.php
- src/helper/Helper_Templates.php
- src/helper/abstract/Helper_Abstract_Options.php
- src/view/html/Settings/tabs.php
Fix issues when plugin translated into other languages
Resolves #663
> Translation js issues

- src/helper/abstract/Helper_Abstract_Options.php
> Don't run ConditionalLogic field through generic sanitisation

- src/helper/abstract/Helper_Abstract_Addon.php
Instead of each Gravity PDF add-on implementing the license key registration and additional links on the plugin page, we'll make this universally via the abstract class.
Resolves #656
> Add universal support for add-ons to show license key registration / links

- src/model/Model_PDF.php
> Ensure no URL parameters when using home_url()

- src/bootstrap.php
- src/helper/Helper_Templates.php
- tests/phpunit/unit-tests/test-helper-templates.php
> Load the correct configuration file is overridden by 'tempalte' URL param

- composer.json
- src/helper/abstract/Helper_Abstract_Addon.php
- src/helper/trait/Helper_Trait_Logger.php
This is especially useful with the add-on Framework
> Add logger Trait to make it easier to add Logging functionality to classes

- src/controller/Controller_Activation.php
Resolves https://github.com/GravityPDF/gravity-pdf/issues/687
> Ensure Controller_Activation is PHP5.2 compatible

- src/assets/js/gfpdf-settings.js
> Check for RTL text and add the switches needed to support it for Chosen

- src/helper/fields/Field_Products.php
> Use the pre-calculated price field for the unit price

- src/model/Model_Mergetags.php
Also reported the problem to Gravity Forms who can fix this upstream.
Fixes #692
> Add check for an unknown form and return early if found

- composer.json
> Update monolog version constraint

- src/helper/fields/Field_Chainedselect.php
> Add support for the Chained Select add-on

- src/helper/fields/Field_Products.php
- src/view/html/PDF/core_template_styles.php
> Right align the unit price and price columns, as well as the totals

- src/model/Model_Install.php
- tests/phpunit/unit-tests/test-pdf.php
> Swap PDF temp directory to use get_tmp_dir()

- api.php
- tests/phpunit/unit-tests/test-api.php
> Add public API endpoint to get the $form_data array

- src/controller/Controller_PDF.php
- src/model/Model_PDF.php
> Set the watermark font to the PDF font

- src/model/Model_Form_Settings.php
- src/view/html/FormSettings/add_edit.php
> Include add-on mergetags / conditional logic support for PDF settings

- src/helper/fields/Field_Discount.php
- src/helper/fields/Field_Product.php
- src/helper/fields/Field_Quantity.php
- src/helper/fields/Field_Shipping.php
- src/helper/fields/Field_Subtotal.php
- src/helper/fields/Field_Tax.php
- src/helper/fields/Field_Total.php
- tests/phpunit/unit-tests/test-form-data.php
Also fix all other product fields show an empty string in the form data array to match our existing data structure.
Resolves #726
> Ensure product quantity field shows the correct value

- .babelrc
- package.json
- src/bootstrap.php
- webpack.config.js
- yarn.lock
Reduce the ReactJS bundle size by 72KB.
> Tree shake Babel Polyfill

- src/controller/Controller_Pdf_Queue.php
This resolves an issue where the notifications were sent even though the PayPal Standard plugin has delaying them. Will also play nicer with other developers who disabled these notifications themselves.
> Don't queue notifications if they've been disabled by another plugin

- .babelrc
- .travis.yml
- README.md
- karma.conf.js
- package.json
- tests/bin/install.sh
- tests/mocha/tests.bundle.js
- yarn.lock
- Fix up issue running unit test installer via Git Bash on Windows
- Also update the GitHub tar.gz URLs
> Test Runner Updates

- .travis.yml
- tests/phpunit/bootstrap.php
- Fix up GF2.3 cleanup issue
- Update Travis build to match new minimum software requirements
> Fix unit tests since minmum software version bump

- src/model/Model_PDF.php
Also add warning to logs about an unauthorized attempt to access a PDF
Resolves #748
> Display Access Denied Message to User

- src/controller/Controller_Shortcodes.php
- src/helper/Helper_Migration.php
- src/helper/abstract/Helper_Abstract_Options.php
- src/model/Model_Form_Settings.php
- src/model/Model_Install.php
- src/model/Model_Mergetags.php
- src/model/Model_PDF.php
- src/model/Model_Settings.php
- src/model/Model_Shortcodes.php
- src/model/Model_Welcome_Screen.php
- src/view/View_Settings.php
Remove unnecessary logs and make the existing logs more relevant.
> Reduce Log File Bloat when using Notices

- src/helper/Helper_Field_Container.php
> Allow power users to toggle the Faux column on and off

- src/assets/css/gfpdf-styles.css
- src/helper/Helper_Options_Fields.php
- src/view/html/Settings/help.php
Also fix up old Gravity Forms links.
Resolves #747
> Remove "Common Problems" and replace with "Common Questions"

- src/assets/js/gfpdf-settings.js
Also fixes merge tag initialisation problem
> Remove GF JS Background Compatibility

- src/model/Model_PDF.php
> Change $lead to $entry so the survey score is correctly included

- src/model/Model_PDF.php
Use PHP's SPL library to recursively clean-up our tmp directory
> Recursively clean-up the PDF temporary directory

- src/view/View_PDF.php
- src/view/html/PDF/page_title.php
- tests/phpunit/unit-tests/test-pdf.php
Page 1 isn't included in the field list so cannot include CSS for it.
Resolves #763
> Add CSS classes to Core templates from page 2+

- src/helper/Helper_Logger.php
> Wrap a try/catch block around our Gravity Forms logger

- src/helper/fields/Field_Subtotal.php
> Get the E-Commerce field's subtotal

- src/assets/js/react/components/Template/TemplateUploader.js
> Fix upload error when file over 5MB but under 10MB

- src/helper/Helper_PDF.php
Works in conjunction with our getter method
> Add PDF setter method

- src/assets/js/gfpdf-settings.js
> Restrict Owner Advanced field is showing/hiding when Public Access is toggled

- src/helper/Helper_Options_Fields.php
> Ensure the `std` value isn't translated

- src/view/View_PDF.php
Ensures the form object gets correctly transformed prior to creating the template mark-up
> Add full support for the Gravity Perk Conditional Date Plugin

- CHANGELOG.txt
- README.txt
- initialisation/README.txt
- src/view/html/Welcome/welcome.php
Mostly string changes for en_US base localization, but also 2 spelling mistakes.
> en_US base localization

- src/helper/Helper_Options_Fields.php
> Use more condensed language in the Background Processing settings

- src/bootstrap.php
- src/controller/Controller_Debug.php
- src/controller/Controller_Install.php
- src/helper/Helper_Data.php
- src/helper/Helper_Options_Fields.php
- src/helper/Helper_PDF.php
- src/helper/Helper_Templates.php
- src/model/Model_Shortcodes.php
- src/model/Model_Templates.php
- tests/phpunit/unit-tests/test-helper-templates.php
- tests/phpunit/unit-tests/test-shortcodes.php
This is a work in progress. Still need to add tests and a `Purge Template Cache` feature to the tools tab.
> Add transient caching to the get_template_info_by_path method

- src/helper/fields/Field_Option.php
Resolves https://github.com/GravityPDF/gravity-pdf/issues/825
> Filter out options unrelated to the current field

- src/model/Model_PDF.php
- tests/phpunit/unit-tests/test-pdf.php
This gives much better coverage than just detecting if the IP address matches 127.0.0.1.
> Ensure the entry IP doesn't match the current server IP

- src/view/html/PDF/core_template_styles.php
> Convert background image URL to local path

- src/deprecated.php
- src/helper/Helper_PDF.php
Resolves https://github.com/GravityPDF/gravity-pdf/issues/858
> Use WordPress' ca-bundle.crt when making cURL requests in mPDF

- src/helper/fields/Field_Form.php
> Add support for "exclude" class in nested form fields

- src/model/Model_Install.php
Resolves https://github.com/GravityPDF/gravity-pdf/issues/864
> Remove mPDF tmp directory writable test

- src/model/Model_Install.php
- tests/phpunit/unit-tests/test-installer.php
> Ensure the mPDF directories are always created

- src/deprecated.php
> Fix up v3 template PHP notices

- src/controller/Controller_PDF.php
Resolves https://github.com/GravityPDF/gravity-pdf/issues/871
> Ensure we pass the first entry ID in legacy v3 URLs

- src/helper/abstract/Helper_Abstract_Options.php
Resolves https://github.com/GravityPDF/gravity-pdf/issues/866
> Include missing mPDF fonts in our font selector

- src/controller/Controller_PDF.php
Resolves #863
*Steps to Reproduce Bug*
Prior to this patch (i.e if you checkout the current `development` branch), the bug can be replicated by doing the following:
1. Install and activate the [SG Optimizer plugin](https://github.com/GravityPDF/gravity-pdf/files/2959996/sg-cachepress.zip) alongside Gravity PDF (checked out to the `development` branch.
2. Select the new "SG Optimizer" menu option from the WP Admin area
3. Select "Frontend Optimzation" in the sub menu and enable the "Minify the HTML Output" option
4. In the PDF Global Settings, [change the Entry View option](https://gravitypdf.com/documentation/v5/user-global-settings/#view) to "Download"
5. [Download an entry's PDF](https://gravitypdf.com/documentation/v5/user-viewing-pdfs/) and after downloading it open with Adobe Reader; …
> Fix conflict with the Minify HTML option for the Siteground Optimizer plugin

- tests/mocha/unit-tests/components/CoreFonts/core.font.container.spec.js
- tests/mocha/unit-tests/components/CoreFonts/core.font.list.results.spec.js
- tests/mocha/unit-tests/components/Template/template.activate.button.spec.js
- tests/mocha/unit-tests/components/Template/template.button.spec.js
- tests/mocha/unit-tests/components/Template/template.close.dialog.spec.js
Issue: #905
Fixed test deprecation code warning in the following file:
- tests/mocha/unit-tests/components/CoreFonts/core.font.container.spec.js
- tests/mocha/unit-tests/components/CoreFonts/core.font.list.results.spec.js
- tests/mocha/unit-tests/components/Template/template.activate.button.spec.js
- tests/mocha/unit-tests/components/Template/template.button.spec.js
- tests/mocha/unit-tests/components/Template/template.close.dialog.spec.js
Run: yarn test
> Fixed Test Warning: Please use `require("history").createHashHistory

- composer.json
- composer.lock
- src/deprecated.php
- src/helper/Helper_Mpdf.php
- src/helper/Helper_PDF.php
- tests/phpunit/unit-tests/test-helper-mpdf.php
Update to the latest version of mPDF and add backwards compatible support to prevent breaking changes.
Resolves #902
Resolves #903
This is a WIP
> Upgrade to mPDF 8.0

- yarn.lock
Issue: #953 
Update yarn.lock indirect dependencies to fix repository warning for potential security vulnerabilities.
> Update yarn.lock file potential security vulnerabilities

- src/assets/js/react/actions/coreFonts.js
- src/assets/js/react/components/CoreFonts/CoreFontButton.js
- src/assets/js/react/components/CoreFonts/CoreFontContainer.js
- src/assets/js/react/components/CoreFonts/CoreFontListSpacer.js
- src/assets/js/react/reducers/coreFontReducer.js
- tests/mocha/unit-tests/react/actions/core.font.spec.js
- tests/mocha/unit-tests/react/components/CoreFonts/core.font.button.spec.js
- tests/mocha/unit-tests/react/components/CoreFonts/core.font.container.spec.js
- tests/mocha/unit-tests/react/reducers/core.font.reducer.spec.js
Issue: #980 
Refactored code of 'Queue process' for core fonts download.
> Refactor Queue process for core fonts download

- .github/README.md
- gulpfile.js
- package.json
Issue: #995 
Fixed package.json script for gulp css watch mode and webpack JS watch mode
run the following scripts:
- yarn run build:css:watch
- yarn run build:js:watch
> Fixed script for gulp css watch mode and webpack JS watch mode

- src/Helper/Fields/Field_Consent.php
Issue: #993 
Consent Description Placement
> Consent Description Placement

- src/assets/js/react/components/CoreFonts/CoreFontContainer.js
- tests/e2e/page-model/global-settings/tools/install-core-fonts/install-core-fonts.js
Issue: #1012 
Ensure download core fonts installer is working properly as well as its test.
Run: 
yarn run test:js
yarn run test:e2e
yarn run test:e2e:headless
> Refactored download core fonts installer as well as its test

- .travis.yml
- bin/json-payload.sh
On Travis CI, the Core Font Payload could show an error if GitHub rate limit hit for unauthenticated users. 
Related #1012
Review Travis CI results
> Add support for GitHub Basic Authentication to prevent Core Font JSON issue

- src/assets/js/react/components/CoreFonts/CoreFontContainer.js
- src/assets/js/react/reducers/coreFontReducer.js
- src/assets/js/react/router/coreFontRouter.js
- src/assets/js/react/sagas/coreFonts.js
- tests/mocha/unit-tests/react/components/CoreFonts/core.font.container.spec.js
- tests/mocha/unit-tests/react/sagas/core.fonts.spec.js
Part of Issue: #1012 
Fixed for download core fonts installer error handling.
> Fixed download core fonts installer error handling

- src/assets/js/react/components/CoreFonts/CoreFontContainer.js
- tests/mocha/unit-tests/react/components/CoreFonts/core.font.container.spec.js
Part of issue: #1012 
Fixed loading spinner and counter as well as JS unit test error.
> Fixed loading spinner and counter as well as JS unit test error

- .travis.yml
- phpunit.xml.dist
[We need to remember to use `--` when passing parameters](https://stackoverflow.com/a/44743871/1614565). 
Watch the results of Travis CI.
This also fixes the AJAX Unit Tests and the PHP Code Coverage tests
> Ensure parameters get passed to npm-scripts correctly in Travis

- src/assets/js/react/actions/coreFonts.js
- src/assets/js/react/components/CoreFonts/CoreFontContainer.js
- src/assets/js/react/reducers/coreFontReducer.js
- tests/mocha/unit-tests/react/actions/core.font.spec.js
- tests/mocha/unit-tests/react/components/CoreFonts/core.font.container.spec.js
- tests/mocha/unit-tests/react/reducers/core.font.reducer.spec.js
> Ensure download coreFonts via URL is working correctly

- src/assets/js/react/components/CoreFonts/CoreFontContainer.js
Updated DocBlock for CoreFontContainer.js
> Update DocBlock for CoreFontContainer.js

- yarn.lock
> Fix handlebars security issue

- src/Model/Model_Settings.php
This will help track down license activation errors
Resolves #923
Enable logging
Try activate a fake license
View log file
> Add better logging for license activation issues

- src/Controller/Controller_Settings.php
- tests/phpunit/unit-tests/test-settings.php
Resolves an issue with users uploading TTF font files for Gravity PDF to the media library.
Fixes #992
Upload a TTF file to the media library
- [ XMy code is easy to read, follow, and understand
> Add proper TTF font file validation

- src/Model/Model_Install.php
> Add pre and post uninstall actions that plugins can hook into

- README.txt
- pdf.php
- src/Helper/Licensing/EDD_SL_Plugin_Updater.php
- src/assets/js/admin/settings/common/doUploadListener.js
- src/assets/js/admin/settings/pdf/handleSecurityConditionals.js
* Bug: Fix Media Manager so it shows all file types on Gravity PDF pages
* Bug: Fix Security PDF settings JS toggle when using translated text
* Dev: Update EDD software licensing class to 1.7.1
> 5.3.2 Patch Release

- src/Controller/Controller_Custom_Fonts.php
- src/Exceptions/GravityPdfDatabaseUpdateException.php
- src/Exceptions/GravityPdfDomainException.php
- src/Exceptions/GravityPdfException.php
- src/Exceptions/GravityPdfFontNotFoundException.php
- src/Exceptions/GravityPdfIdException.php
- src/Exceptions/GravityPdfModelNotUpdatedException.php
- src/Exceptions/GravityPdfRuntimeException.php
- src/Exceptions/GravityPdfShortcodeEntryIdException.php
- src/Exceptions/GravityPdfShortcodePdfConditionalLogicFailedException.php
- src/Exceptions/GravityPdfShortcodePdfInactiveException.php
- src/Helper/Fonts/FlushCache.php
- src/Helper/Fonts/SupportsOtl.php
- src/Helper/Fonts/TtfFontValidation.php
- src/Helper/Helper_Data.php
- src/Model/Model_Custom_Fonts.php
- src/bootstrap.php
- tests/phpunit/unit-tests/Controller/Test_Controller_Custom_Fonts.php
- tests/phpunit/unit-tests/Helper/Fonts/Test_FlushCache.php
- tests/phpunit/unit-tests/Model/Test_Model_Custom_Fonts.php
> Add docblocks, native type checks and exceptions for Custom Font API

- package.json
- src/assets/js/react/components/FontManager/AdvancedButton.js
- src/assets/js/react/components/FontManager/Body.js
- src/assets/js/react/router/fontManagerRouter.js
- yarn.lock
Issue: #1091 
This PR resolves React JS console warnings in Gravity PDF admin pages
> Fix react deprecated console warnings

- pdf.php
- src/Controller/Controller_Settings.php
- src/Controller/Controller_System_Report.php
- src/Model/Model_Settings.php
- src/Model/Model_System_Report.php
- src/View/View_System_Report.php
- src/bootstrap.php
- tests/phpunit/unit-tests/Controller/Test_Controller_Custom_Fonts.php
- tests/phpunit/unit-tests/Controller/Test_Controller_System_Report.php
- tests/phpunit/unit-tests/Model/Test_Model_System_Report.php
- tests/phpunit/unit-tests/View/Test_View_System_Report.php
- tests/phpunit/unit-tests/test-ajax.php
Added new Model for the system report.
Updated bootstrap file to inject the new Model.
Re design system report interface based on GF's 2.5 beta version.
Form -> System Status
> GF 2.5 Updated System Status.

- src/Helper/Helper_PDF_List_Table.php
- src/assets/js/admin/settings/form/list/setupAJAXListDuplicateListener.js
- src/assets/js/admin/settings/form/list/setupAJAXListStateListener.js
- src/assets/scss/Pages/_pdf-list.scss
https://github.com/GravityPDF/gravity-pdf/issues/1115#issuecomment-692348494
Replace references on png to svgs. Update default file extension from png to svg. 
Added proper css on table headings.
> RE: Issue # 1115

- src/assets/scss/Component/_number.scss
https://github.com/GravityPDF/gravity-pdf/issues/1114#event-3765578943
Adjusted width from 5rem to 5.2rem.
> RE : Issue #1114

- src/Helper/Helper_PDF_List_Table.php
- src/Model/Model_Form_Settings.php
- src/assets/js/admin/settings/form/list/setupAJAXListDuplicateListener.js
- src/assets/js/admin/settings/form/list/setupAJAXListStateListener.js
- src/assets/scss/Pages/_pdf-list.scss
Remove returned $src variable (unused).
Update simple jQuery script to toggle text and svg class.
Update overall layout from external svg to internal.
Lints.
> GF-2.5beta2.2 PDF List Toggle Update

- src/assets/js/react/utilities/FontManager/associatedFontManagerSelectBox.js
- tests/e2e/pdf-settings/appearance/paper-size-field.test.js
- tests/e2e/tabs/general-settings/default-paper-size-field.test.js
- tests/e2e/tabs/general-settings/default-template-field.test.js
- tests/e2e/utilities/page-model/helpers/pdf.js
- tests/e2e/utilities/page-model/tabs/general-settings.js
Resolves #1156 
Fixed font selection bug
> Fix font manager selection bug

- src/assets/js/react/actions/fontManager.js
- src/assets/js/react/components/FontManager/FontListItems.js
- src/assets/js/react/reducers/fontManagerReducer.js
- tests/js-unit/react/actions/fontManager.test.js
- tests/js-unit/react/components/FontManager/FontListItems.test.js
- tests/js-unit/react/reducers/fontManagerReducer.test.js
Issue: #1154 
Display selected font at the top of the font list automatically.
> Move selected font at the very top of the font list

- src/assets/js/react/components/FontManager/FontListItems.js
- src/assets/js/react/components/FontManager/FontManagerBody.js
- src/assets/js/react/utilities/FontManager/associatedFontManagerSelectBox.js
- tests/e2e/pdf-settings/appearance/font-field.test.js
- tests/e2e/pdf-settings/appearance/font-size-field.test.js
- tests/e2e/pdf-settings/appearance/paper-size-field.test.js
- tests/e2e/tabs/general-settings/background-processing-field.test.js
- tests/e2e/tabs/general-settings/default-font-field.test.js
- tests/e2e/tabs/general-settings/default-font-size-field.test.js
- tests/e2e/tabs/general-settings/default-paper-size-field.test.js
- tests/e2e/tabs/tools/fonts-field.test.js
- tests/e2e/utilities/page-model/helpers/font-manager.js
- tests/e2e/utilities/page-model/helpers/pdf.js
- tests/js-unit/react/components/FontManager/FontListItems.test.js
- tests/js-unit/react/components/FontManager/FontManagerBody.test.js
Issue: #1161 
Fixed font manager incorrectly set font bug.
> Fix font manager incorrectly set font bug

- src/Helper/Helper_Abstract_Options.php
Fix GF beta 3 styling bug for toggle switch button
> GF 2.5 beta 3 - Toggle switch button styling bug

- bin/vendor-prefix.sh
- tests/e2e/global-settings/tools/fonts/manage-fonts.test.js
- tests/e2e/page-model/global-settings/tools/fonts/fonts.js
- tests/e2e/page-model/helpers/pdf.js
Get automated tests working again
> Always run PHP Scoper using PHP7.4 in CI

- src/assets/js/react/bootstrap/templateBootstrap.js
- src/assets/js/react/gfpdf-main.js
Issue: #1112 
Fixed double Ajax Requests after uploading a new template and selecting it.
> Fixed template double spinner bug

- .github/README.md
- .github/workflows/phpunit.tests.yml
- bin/vendor-prefix.sh
- composer.json
- composer.lock
- package.json
- src/Deprecated/Vendor_Aliasing.php
- src/autoload.php
Update our automated test runners to only test the supported PHP versions.
GitHub Actions will do it all.
> Adjust the tested PHP versions for GitHub actions

- src/assets/js/react/bootstrap/coreFontBootstrap.js
- src/assets/js/react/bootstrap/helpBootstrap.js
- src/assets/js/react/bootstrap/templateBootstrap.js
- src/assets/js/react/router/templateRouter.js
Update static string with translatable variable from Helper_Data
#1207
> Update text with translatable variable.

- src/Helper/Helper_Abstract_Options.php
- tests/e2e/utilities/page-model/tabs/license.js
Issue: #1144 
Updated license tab success and error classes
> License tab - Invalid license error message bug

- src/assets/js/react/bootstrap/templateBootstrap.js
> Template manager - Update template list sequencing bug

- src/View/View_Form_Settings.php
- src/assets/js/react/utilities/PdfSettings/addEditButton.js
> Expand all Sections by Default on Add/Update PDF Settings Page

- src/assets/js/admin/settings/common/setupDynamicTemplateFields.js
- src/assets/js/react/utilities/PdfSettings/addEditButton.js
> Fix floating add/edit button bug

- src/Model/Model_System_Report.php
- src/bootstrap.php
- tests/phpunit/unit-tests/Model/Test_Model_System_Report.php
This commit also include update on unit test.
Utilize helper template for the working pdf directory.
#1229
> System Report : Multisite path support.

- src/assets/js/react/gfpdf-main.js
- src/assets/js/react/utilities/PdfList/autoSelectShortcode.js
> Auto select shortcode field

- src/assets/js/admin/settings/form/list/setupAJAXListDuplicateListener.js
- src/assets/js/admin/settings/form/list/setupAJAXListStateListener.js
> Fix PDF active and inactive state bug

- src/assets/js/react/utilities/PdfSettings/addEditButton.js
> Fix extra update button bug

- src/assets/scss/Component/_rich-text.scss
- src/assets/scss/Pages/_pdf-settings.scss
- src/assets/scss/RTL/Component/_rtl-rich-text.scss
- src/assets/scss/RTL/Pages/_rtl-pdf-settings.scss
- src/assets/scss/gfpdf-styles.scss
> Missing Mergetag Selector on Rich Text Fields

- src/assets/scss/Pages/_pdf-settings.scss
- src/assets/scss/RTL/Pages/_rtl-pdf-settings.scss
Issue: Ensure merge tags box selector will look good on small screen and RTL view.
> Merge tags box css enhancement

- pdf.php
In Gravity PDF 6.0, we bump all the minimum requirements for WP, PHP, and Gravity Forms to future-proof the plugin. We will also support Gravity PDF 5.0 for at least 12 months after the release (maybe longer). To ease users into it, if they install 6.0 and their site doesn't support it (and they don't want to fix the problems), this PR provides a downgrade feature to rollback to the latest v5 version of Gravity PDF. 
Resolves #1113 
Resolves #1132 
1. Install Gravity PDF 6.0
2. Install Gravity Forms 2.4
3. Activate both plugins
4. Click the Downgrade Gravity PDF prompt that is shown
5. v6.0 should be rolled back to v5
> Show downgrade notice if some minimum requirements aren't met

- .github/workflows/javascript-tests.yml
- src/Helper/Helper_Abstract_Options.php
- src/Helper/Helper_Data.php
- src/Helper/Helper_PDF_List_Table.php
- src/View/html/Actions/core_font.php
- src/View/html/FormSettings/list.php
- src/View/html/GravityForms/fieldset.php
- src/View/html/PDF/entry_detailed_pdf.php
- src/assets/js/react/bootstrap/templateBootstrap.js
- src/assets/js/react/components/CoreFonts/CoreFontListResults.js
- src/assets/js/react/components/FontManager/AddFont.js
- src/assets/js/react/components/FontManager/AdvancedButton.js
- src/assets/js/react/components/FontManager/FontList.js
- src/assets/js/react/components/FontManager/FontListItems.js
- src/assets/js/react/components/FontManager/SearchBox.js
- src/assets/js/react/components/FontManager/UpdateFont.js
- src/assets/js/react/components/Template/TemplateActivateButton.js
- src/assets/js/react/components/Template/TemplateButton.js
- src/assets/js/react/components/Template/TemplateDeleteButton.js
- src/assets/js/react/components/Template/TemplateList.js
- src/assets/js/react/components/Template/TemplateListItem.js
- src/assets/js/react/components/Template/TemplateSearch.js
- src/assets/js/react/components/Template/TemplateUploader.js
- tests/e2e/tabs/tools/fonts-field.test.js
- tests/e2e/utilities/page-model/helpers/font-manager.js
- tests/e2e/utilities/page-model/helpers/template-manager.js
- tests/js-unit/react/components/CoreFonts/CoreFontListResults.test.js
- tests/js-unit/setupTests.js
- tests/phpunit/unit-tests/Model/Test_Model_Pdf_Meta_Box.php
Complete initial accessibility audit on codebase.
Resolves https://github.com/GravityPDF/gravity-pdf/issues/1028
These changes touch many places in the codebase, so checking there is no display issues or functionality problems will be important (the E2E tests should catch these though, if they were all working...)
> WCAG 2.1 Development

- src/assets/scss/Component/_template-manager.scss
> Template manager error message CSS adjustment

- src/assets/js/react/components/Template/TemplateUploader.js
> Enable error message for exceeding maximum limit of file size
