src/helper/Helper_Options.php, tests/unit-tests/test-options-api.php
Brought to our attention in #13, we debugged the issue and found the sanitization wasn't being done correctly. 
This patch fixes the issue (and fixes #13 too).
=> Resolve sanitization problems for our global settings pages

src/model/Model_PDF.php, src/views/html/PDF/entry_detailed_pdf.php, src/views/html/PDF/entry_list_pdf_multiple.php, src/views/html/PDF/entry_list_pdf_single.php, tests/unit-tests/test-pdf.php
The Detailed Entry page had corrupt PDF links when the view was set to "Download". Update get_pdf_display_list() so it returns both view and download links then toggle which one in the view.
=> View / Download Links Fail when "Download" is default option

tests/phpunit/bootstrap.php
Bug: Handle Gravity Forms table cleanup right before the setup (instead of on shutdown) to prevent any problems when unit tests fail
Bug: Ensure we disable Xdebug stack trace on the CLI so as not to blow out the phpunit output when errors occur
=> Unit Test Gravity Forms Cleanup

initialisation/templates/zadani.php, src/controller/Controller_PDF.php, src/helper/Helper_Misc.php, src/helper/Helper_PDF.php, src/helper/fields/Field_Quiz.php, src/model/Model_PDF.php, src/views/View_PDF.php, src/views/html/PDF/core_template_styles.php, src/views/html/PDF/entry_list_pdf_multiple.php, tests/phpunit/unit-tests/test-helper-misc.php, tests/phpunit/unit-tests/test-pdf.php
- Steamline the PDF templates so core styles like font, colour, size and headers/footers don't need to be manually set by the user
- Make $gfpdf available to templates automatically
- Preprocess header/footer settings so users don't need to do so via the template
Fixes #39, #41, #57, #42
Remove the "!important" tag from the page font color
=> Steamline Template Variables and Core Styles

README.md, src/model/Model_PDF.php
Fixed references in the plugin to old GitHub repo name. 
Also fixed any links in current documentation. See https://github.com/GravityPDF/v4-documentation/commit/2c74ed9a21b19a7fc13fe86b834b91295ac25ad4
=> Update any references to the old GitHub URL.

src/helper/abstract/Helper_Abstract_View.php, src/views/View_Actions.php, src/views/View_Form_Settings.php, src/views/View_PDF.php, src/views/View_Settings.php, src/views/View_Shortcodes.php, src/views/View_Welcome_Screen.php
While reviewing issue #50 we found there was unnessisary __construct() calls in the classes that extended `Helper_Abstract_View`. A general clean up of this behaviour was done, as well as rectifying the naming conflict mentioned in #50.
Fixes #50
=> Cleanup our View layer and fix the $data reference conflict with our Helper_Data class

src/helper/Helper_PDF_List_Table.php
This change makes it much easier for users to see specifically what PDF is being displayed on a particular confirmation / notification. Before, this was hard to determine just from the ID.
Resolves #37
=> Add the PDF name as a shortcode attribute

src/views/html/PDF/entry_list_pdf_multiple.php, src/views/html/PDF/entry_list_pdf_single.php
The PDF text on the entry list page has always been "View PDF" or "View PDFs". Now there's the option to change the default behaviour to 'download' a PDF we've added appropriate text "Download PDF" and "Download PDFs" to account for this.
Fixes #24.
=> Add "Download PDF" text when global setting is 'download' on entry list

src/controller/Controller_PDF.php, src/helper/Helper_Options_Fields.php, src/model/Model_PDF.php, tests/phpunit/unit-tests/test-pdf.php
While reviewing issue #19 we realised that the PDF public_access logic wasn't configured correctly. This was correctly fixed using a filter and the new function was unit tested. Along with this, the public_access field was enabled by default (not by a filter) and adequate warnings were included for the user.
Resolves #19.
=> Fix Public Access bug and enable the field by default

src/bootstrap.php, src/helper/Helper_Singleton.php, tests/phpunit/unit-tests/test-singleton.php
We decided against making our MVC classes singletons themselves due to the problems this presented when doing so in an abstract way (http://stackoverflow.com/questions/8907460/php-5-3-abstract-singleton-class-and-childrens). 
Since we just need to provide access to the original objects we build a helper class that can be used to store and retrieve the classes when needed. This allowed an easier way for developers to interact with the original classes – the main reason is to allow the manipulation of actions/filters.
This PR effectively resolves #102 and #21.
=> Add Singleton-style helper class to allow access to original objects

src/assets/js/gfpdf-settings.js, src/controller/Controller_Settings.php, src/helper/Helper_Misc.php, src/model/Model_Settings.php, src/views/View_Settings.php, src/views/html/Settings/system_status.php, tests/phpunit/unit-tests/test-ajax.php
Non Apache systems aren't protected because they don't support .htaccess. Add a notice about it in the system status when this is detected and link to our documentation on how to move the tmp directory to a non-public directory. Used AJAX to prevent page loading problems.
Resolves #97 
Resolves #28
=> Add warning system about insecure tmp directory

tests/phpunit/unit-tests/test-form-data.php
This partially resolves #133 but our test suite install script only works in a unix environment.
=> Allow Windows-based users to run phpunit if the suite is installed

src/assets/js/gfpdf-settings.js
- Add support for WordPress 4.4 with our list item visibility
- Limit deleting of PDFs to one at a time. This prevents conflicts with our delete dialog box which stores our original element
Fixes #131
=> Resolve PDF list item problems

src/controller/Controller_PDF.php, src/helper/Helper_PDF.php, src/view/View_PDF.php, src/view/html/PDF/core_template_styles.php
Currently the template HTML and the default styles just returned together (after the closing `</html>` tag) but in future it would be good to insert it after the opening `<body>` tag (need to replace querypath library first though - probably use Symphony).
Fixes #147
=> Include our default template styles with our in-browser HTML viewer.

src/assets/css/gfpdf-styles.css
The section borders didn't appear in WP4.4. Updated our CSS to fix this.
Resolves #137
=> Update Welcome Page CSS to fix regression in WP4.4

src/helper/fields/Field_Products.php
This is to prevent the header being automatically duplicated when split across pages
=> Remove the <thead> from the product table 

src/model/Model_Form_Settings.php
This prevents conflicts on the template tab when adding new PDF settings.
Fixes #195
=> Allow PID to be loaded from the GET and POST data 

src/helper/fields/Field_List.php
By default any <thead> elements gets duplicated on the next page if the table crosses multiple pages. We didn't want this so wrap it in a <tbody> and give the head and the main content a class name.
Fixes #202
=> Fix list thead issue in mPDF

src/helper/Helper_Misc.php
When plain text was passed to the function is created problems. We'll only do the DOM manipulation when an image is actually found in the DOM.
=> Fix regression caused when updating the header/footer image code

src/controller/Controller_PDF.php, src/helper/Helper_PDF.php, src/view/View_PDF.php, tests/phpunit/unit-tests/test-pdf.php
This issue was caused because we were writing our core styles (which includes header/footer details) to the PDF before our template. This caused the software to create a new page (with no header/footer). The solution was to write the styles at the same time.
This may create a regression with v3 templates and we'll need to get a close eye for any issues.
Fixes #206
=> Fix header/footer manual display issue

initialisation/template.css, src/templates/blank-slate.php, src/templates/focus-gravity.php, src/templates/rubix.php, src/templates/zadani.php
We've stripped out all unnecessary markup from the PDF templates. We didn't need <body> or </html> tags (it just gets confusing for the end user). We also refined some of the comments.
Resolves #209
Remove note about backwards compatible variables
=> Refine the template markup

src/assets/js/gfpdf-settings.js
This prevents issues saving the old PDF template settings.
Fixes #210
=> Remove the custom appearance HTML from the form when not supported

src/model/Model_Install.php
Also resolves $blog_id bug which was being defined after it was used resulting in an error.
Resolves #217
Resolves #218
Fix the multisite template variables being passed to the filter
Fixes #219
=> Fix template and multisite filters

src/depreciated.php, src/helper/Helper_Migration.php, src/helper/Helper_Misc.php, src/helper/abstract/Helper_Abstract_Options.php, src/model/Model_Settings.php, src/view/View_Settings.php, tests/phpunit/unit-tests/test-migration.php
Update any single references to the path or url. We left a lot of the template/config/image paths untouched as it checks multisite, then the single site directory before looking in the plugin folder.
Fixes #222
=> Consolidate the multisite path and url into a method in misc

src/helper/fields/Field_Name.php
This is pre 1.9 when Gravity PDF name fields had a single option. They no longer do this but we need to support legacy forms.
=> Add backwards compat on the name field

src/bootstrap.php, src/depreciated.php, src/helper/fields/Field_Products.php, src/view/View_PDF.php, tests/phpunit/unit-tests/test-pdf.php
Our premium v3 templates accepts the returned markup as an array and parses it to create columns. The way we had it set up in v4 was just to return the entire string.
To get around this issue we moved a stripped down version of the field output to depreciated.php.
Fixes #227
Add additional backwards compatible tweaks to ensure a smoother transition for more users
=> Create markup closer to our v3 style when using depreciated methods

src/model/Model_PDF.php
We needed to add a filter to ensure notifications compatibility with our Tier 2 add-on. It was a special kind of filter as it didn't pass in the $filename so we'll only process it when our advanced template option is enabled.
Resolves #230
=> Add notifications compatibility for our T2 add-on

src/helper/Helper_PDF.php
Also tested with W3 Total Cache and WP Super Cache without issue.
Fixes #234
=> When viewing PDF set DONOTCACHEPAGE parameter to prevent WP Rocket conflict

api.php, tests/phpunit/unit-tests/test-slow-pdf-processes.php
Instead of requiring the Entry and PDF Settings objects you can now just pass in the entry ID and PDF ID and get a PDF generated.
Resolves #236
=> Make the API create_pdf() method easier for developers to use

src/helper/Helper_Misc.php, src/model/Model_Form_Settings.php, src/templates/blank-slate.php, src/templates/focus-gravity.php, src/templates/rubix.php, src/templates/zadani.php, tests/phpunit/unit-tests/test-form-settings.php, tests/phpunit/unit-tests/test-helper-misc.php
This allows devs to move their core template logic into reusable code blocks with ease.
Fixes #259
=> Pass in the current template's initialised config class

src/bootstrap.php
As the settings JS is a dependency of 'gfpdf_js_v3_migration' this shouldn't be an issue.
=> Only localise the script on the settings. 

src/controller/Controller_Settings.php
- Only run the action is our $_POST['gfpdf_settings'] value exists and prevent an nonce issue .
- Add tool tab action that can be used by users
=> Add better checks to Tool page actions and developer action

src/assets/css/gfpdf-styles.css, src/helper/Helper_PDF_List_Table.php
Allow developers to add custom actions when there's no method specifically targeted at a column (i.e on the default column fallback method).
Remove the fixed width on the columns to prevent problems when developers add additional columns via filters.
=> Clean up the HTML markup, filters and comments for our PDF list.

src/model/Model_Form_Settings.php, src/view/html/PDF/core_template_styles.php, tests/phpunit/unit-tests/test-form-settings.php
Allow developers to set their own external callbacks for the core methods and add an action to output core styles.
Fix up unit test to account for the new order or filters when doing sanitization
=> Allow external callbacks on 'core' PDF template settings

src/bootstrap.php, src/depreciated.php, tests/phpunit/bootstrap.php, tests/phpunit/unit-tests/test-depreciated.php
Load the plugin on the `after_setup_theme` action instead of`plugins_loaded` to allow themes to tap into all our actions / filters via their theme.
Ensure our unit testing stubs aren't created until after Gravity PDF loads.
=> Load core plugin on `after_setup_theme` instead of `plugins_loaded`

src/model/Model_Install.php
Rename the multisite filters to match our standard filters and remove the duplicate blog_id parameter.
Pull out the secondary data into their own shorter variables to make it easier for read the filters
=> Ensure tmp and font folders are removed during uninstall. Also tidy up template filters.

src/controller/Controller_PDF.php, src/model/Model_PDF.php, src/view/View_PDF.php, src/view/html/PDF/core_template_styles.php, src/view/html/PDF/form_title.php, src/view/html/PDF/page_title.php, tests/phpunit/unit-tests/test-pdf.php
- Change the middleware filter order
- Include missing middleware from comments
- Create separate HTML files for our title and page mark-up
- Include GPL notice in core_template_styles.php
- Reorder the variables in our gfpdf_post_save_pdf hook and include the $filename.
- Change $pdf to $settings to be more accurate
- Change $pdf to $settings to be more accurate
- Fix up bug when enabling public access
- Ensure unit tests pass
=> Housekeeping for our PDF generator code

src/controller/Controller_PDF.php, src/helper/Helper_Misc.php, src/helper/Helper_PDF.php, src/model/Model_PDF.php, src/view/View_PDF.php, tests/phpunit/unit-tests/test-helper-misc.php, tests/phpunit/unit-tests/test-pdf.php, tests/phpunit/unit-tests/test-slow-pdf-processes.php
There was a major issue with the way we were parsing the legacy Tier 2 add-on. It appeared to work correctly when only one Tier 2 template was being run but once you started using multiples it fell to pieces.
This patch reimagines how the legacy Tier 2 compatibility should function in Gravity PDF 4.0. Instead of handling it inside our Helper_PDF class, we are instead bypassing that functionality and doing the checks before hand in our Model_PDF and View_PDF functions (one for saving and one for viewing).
We also fixed a clean-up issue when resending PDFs via the admin area.
Add unit tests and optimise code
Resolves #289
=> Fix for Tier 2 add-on attachments

src/helper/abstract/Helper_Abstract_Options.php, src/view/html/Settings/tools.php
- Include settings fields on tools tab so our sanitization method runs correctly
- Prevent the saving of any registered fields on the tools tab (it's just for actions).
Resolves #280
=> Prevent saving of tools form fields in our global PDF settings

src/helper/Helper_Misc.php
Older versions of multisite installations didn't use a standardised upload path which messes with our folder structure. We'll switch to the initial primary blog (which did use the /wp-content/uploads/ directory) and then restore the current blog at the end.
Note: because BLOG_ID_CURRENT_SITE can be changed and the 'upload_path' option doesn't change with it we opted to hardcode the ID instead.
Resolves #271
=> Fix legacy multisite template folder issue

src/assets/js/gfpdf-settings.js, src/helper/Helper_Options_Fields.php, src/view/View_PDF.php, src/view/html/FormSettings/add_edit.php
- Hide the appearance tab when using a Tier 2 template
- Prevent the loading of the core template styles when usign a Tier 2 template
- Remove the filter "gfpdf_enable_advanced_template_field" because we want to automate this much more
=> Prevent Appearance defaults loading on legacy Tier 2 templates

.travis.yml, pdf.php
Gravity PDF 4.0 is such a major release that we can afford to also bump up the version requirements.
We really wanted to bump this up to an actively supported version of PHP (http://php.net/supported-versions.php) but with WordPress supporting PHP5.2+ (and making no moves to increase this) we had to strike a balance.
The initial release will require PHP 5.4 which will strike a better balance.
=> Bump PHP minimum version up to 5.4

src/assets/css/gfpdf-styles.css, src/controller/Controller_Welcome_Screen.php, src/model/Model_Welcome_Screen.php
- Fix up display issues in WordPress 4.5
- Move the hiding of our welcome pages to the "admin_head" action which stops an authentication error for some users
- Change the minimum capability of these pages to match that of our controller class
Partially resolves the problem in #324. Haven't been able to track down (or replicate) why an update from another plugin triggered the redirect as of yet.
=> Fix up welcome page bugs

src/assets/js/gfpdf-settings.js
This problem occurs when a template is saved with the Advanced Template option enabled. Then, when you try change the template to another the Appearance tab doesn't show up because the Advanced Template option is still activated. To resolve this I reset that option to No on template change. It's a legacy option anyway so I'm not concerned about doing it this way.
Fixes #333
=> Fix issue with Appearance tab not showing up on template change

src/assets/js/gfpdf-settings.js
=> Fix up parse error suffered in Chrome when the tinyMCE editor isn't found.

src/controller/Controller_PDF.php, src/depreciated.php, src/helper/Helper_Form.php, src/helper/Helper_Misc.php, src/helper/abstract/Helper_Abstract_Fields.php, src/helper/abstract/Helper_Abstract_Form.php, src/model/Model_PDF.php, tests/phpunit/unit-tests/test-pdf.php
This makes it much simpler for us to fix https://github.com/GravityPDF/gravity-pdf/issues/358. It also makes more sense that tags are handled by our form helper class.
=> Move mergtag processing function to Helper_Form

src/helper/Helper_Migration.php, src/model/Model_Form_Settings.php, src/model/Model_PDF.php, tests/phpunit/unit-tests/test-form-settings.php, tests/phpunit/unit-tests/test-pdf.php
- Also omit Save and Continue notification(s) from our notifications list
- Ensure save and continue notification cannot be imported during v3 migration
- Add appropriate unit tests
Resolves #360
=> Prevent PDF trying to be generated when using "save and continue" feature

src/helper/Helper_Misc.php, src/model/Model_PDF.php, src/model/Model_Settings.php, tests/phpunit/unit-tests/test-helper-misc.php
mPDF caches the processed font files and saves it for later (see https://github.com/GravityPDF/gravity-pdf/pull/193). The problem occurs when a user drops a font file directly in the /fonts/ directory without installing it via our font installer (we're most effected by this when doing PDF integrations), loads some PDFs but then decides to install the font via the installer with the same name. Because of the font cache this causes problems. To get around this issue we are no clearing the fontdata cache when fonts are installed, edited or deleted.
While reviewing this problem we found that font files assigned to a group could still be included in mPDFs font array because we were only checking the top array key. To fix this problem we now recursively look through the multidimensional array …
=> Fix font caching bug and duplicate custom font types

src/controller/Controller_Activation.php
=> Resolves fatal error when permalinks aren't enabled and you try deactivate plugin

src/helper/Helper_Field_Container_Void.php, src/templates/blank-slate.php, src/templates/focus-gravity.php, src/templates/rubix.php, src/templates/zadani.php, src/view/View_PDF.php
This allows developers more freedom to style the PDF as they see fit.
Ensure PDF templates have CSS Ready Class support enabled by default
=> Add switch to disable CSS Ready Class support

src/helper/Helper_Field_Container.php, src/helper/Helper_Field_Container_Void.php, src/view/View_PDF.php, tests/phpunit/unit-tests/test-field-container.php
Output placeholder HTML if empty or hidden field is part of CSS Ready Class columns and the row is currently open and the field will fit in that row without opening another row.
Set public methods to do nothing in our Container_Void class
Add unit tests for changes
Resolves #381
=> Fix CSS Ready Class Columns when field is hidden or empty

src/model/Model_Welcome_Screen.php
The welcome screen doesn't need any protection. Give users full access to hidden page if they know direct link.
Only users with the 'activate_plugins' capability will be automatically redirected to page.
=> Allow subscriber access to PDF welcome screen

major-upgrade-checker.php, pdf.php
Because 4.0 has bumped up the system requirements a lot we'll prevent users upgrading to 4.0 releases if they don't meet the minimum system requirements.
=> Prevent Gravity PDF update showing if major version requirements are not met.

src/helper/abstract/Helper_Abstract_Fields.php, src/helper/fields/Field_Address.php, src/helper/fields/Field_Section.php
Sub-fields in address fields can be hidden but Gravity Forms can save defaults like State and Country still. To prevent this we'll check empty values for active sub-fields only.
We also check all sub-fields for values before including them in our HTML output array.
Adjust section break so it utilises our custom empty field checker.
=> Correctly calculate if address field is empty

src/assets/js/gfpdf-backbone.js, src/helper/abstract/Helper_Abstract_View.php, src/view/html/Settings/help.php, src/view/html/Settings/tools.php, tests/phpunit/unit-tests/test-mvc-abstracts.php
This issue occurred because PHP is parsing our underscore JS code as PHP because the PHP INI asp_tags setting is enabled.
The fix was to override the underscore template delimiters and replace them with something else. We chose Handlebars-ish syntax.
Resolves #417
=> Fix PHP ASP Tag / Underscore template tag conflict

src/helper/fields/Field_Checkbox.php, src/helper/fields/Field_Radio.php
This is because these fields are set by the site owner and not the end user so it's presumed to be trusted. The exception to this is user-defined values in Radio fields which allows the "other" option.
With that said, all HTML is run through wp_kses_post() to prevent any nasty surprises.
Resolves #415
=> Allow Radio and Checkbox values to show HTML in PDFs

src/helper/fields/Field_Address.php
When the address field input IDs are an interger / float it was
putting off our address lookup in is_empty(). Case the ID as a string
to correct the problem.
Fixes #429
=> Fix address lookup in is_empty()

src/helper/Helper_Misc.php, src/helper/Helper_QueryPath.php, src/helper/fields/Field_Quiz.php, tests/phpunit/unit-tests/test-helper-misc.php, tests/phpunit/unit-tests/test-query-path.php
This change allows UTF-8 encoded strings to work correctly.
Instead of swapping from htmlqp() to html5qp() we have abstract the
html5qp() function to a Helper Class and forced it to always load HTML from
a string. This prevents issues with loading content that contains no HTML markup.
Resolves #452
=> Change Query Path Usage to use HTML5 Parser

src/templates/blank-slate.php, src/templates/focus-gravity.php, src/templates/rubix.php, src/templates/zadani.php
This prevents conflicts with our default $config variable that's passed into every template that has one.
Resolves #451
=> Change our HTML config variable to $html_config

src/helper/Helper_Misc.php, tests/phpunit/unit-tests/test-helper-misc.php
Run headers / footers through wp_kses_post() and wpautop() to:
1. Strip any unfriendly HTML
2. Add appropriate new line HTML
Resolves #472
=> Fix new line issues in Header / Footers

src/model/Model_Form_Settings.php
=> Use the current PDF active state when saving (if it exists)

src/model/Model_PDF.php
This is done by first decoding the string after processing the mergetags and then running our strip invalid characters method to ensure consistency.
Fixes #475
=> Fix PDF filename encoding issue with merge tags

.travis.yml, src/helper/abstract/Helper_Abstract_Options.php, src/model/Model_Shortcodes.php, tests/phpunit/unit-tests/test-installer.php, tests/phpunit/unit-tests/test-options-api.php, tests/phpunit/unit-tests/test-shortcodes.php
These problems were flagged by our automated tests. There may be more and we'll do further tests when WordPress adds full support for PHP7.1 (currently PHP notices showing).
Resolves #495
=> Resolve string to array conversion issues for PHP 7.1

pdf.php, tests/phpunit/unit-tests/test-pre-checks.php
This should hopefully fix the false positive in the ConfigServer exploit Scanner software.
Fixes #500
=> Rename check_wordpress() to is_compatible_wordpress_version()

src/helper/abstract/Helper_Abstract_Options.php, tests/phpunit/unit-tests/test-options-api.php
This allows users to use merge tags in attributes in the Header / Footer rich text editors (and any others).
Note: Devs should run the field through wp_kses_post() on output to correctly sanitize
Resolves #492
=> Don't apply sanitization on input of rich text editor settings

src/model/Model_PDF.php
Instead of passing the forward slash directly (might be causing problems for some users - see https://wordpress.org/support/topic/found-v4-0-5-bug/), we are hard coding it after the home_url() function.
This matches the setup we used in Gravity PDF 4.0.4 so should hopefully resolve any conflicts with missing slashes in the URL.
=> Explicitly set a forward slash after the home_url()

src/model/Model_Settings.php
Instead of blindly checking for a 200 status response we also read the body of the response and see if it matches what we saved to the file. This will prevent problems with any redirects in place, and should prevent all false positives.
Fixes #519
=> Add additional check to our PDF tmp directory test

src/controller/Controller_Install.php, src/controller/Controller_Welcome_Screen.php, tests/phpunit/unit-tests/test-welcome-screen.php
Previously we restricted this to only show when updating to a minor release (4.x), but many missed out because we pushed our patches fairly quickly. That meant that even though they updated to a new minor release they didn't see the update message because they jumped straight to 4.x.x.
This patch resolves this issue by comparing the old and the new version numbers and seeing if they jumped to a new minor release.
It also prevents the update screen showing if they downgrade.
Resolves #514
=> Redirect to our update screen when the user updates to a new major or minor release

src/bootstrap.php, src/controller/Controller_Mergetags.php, src/model/Model_Mergetags.php, tests/phpunit/unit-tests/test-mergetags.php
In certain circumstances it's useful to just get the Gravity PDF URL which is the purpose of the new {Name:pdf:ID} mergetag. It will function much like the [gravitypdf] shortcode in that it validates a PDF config before displaying the URL. If it isn't valid the merge tag is stripped and an error is placed in the log (Requires the Gravity Forms Logging plugin).
Resolves #404
=> Add a {Name:pdf:ID} Merge tag

src/helper/fields/Field_Products.php
The foreach loop threw an error when the products array is empty. This is because our `is_empty()` check was only seeing if there WERE product fields in the form and not IF those fields were filled in.
Fixes #523
=> Resolve PHP error when no products completed in the table

src/assets/js/gfpdf-settings.js, src/helper/Helper_Misc.php, src/model/Model_Actions.php, src/model/Model_Form_Settings.php, src/model/Model_Settings.php, tests/phpunit/unit-tests/test-ajax.php
We're now using Helper_Misc::handle_ajax_authentication for all AJAX authentication which checks user capabilities and does an Nonce check (prevents CORS).
We also adding missing unit tests for AJAX endpoints and fixed up an endpoint that didn't have an nonce.
Resolves #515
=> Standardise all AJAX authentication to prevent repeat code

src/view/View_PDF.php
The WP External Links plugin conflicts with Gravity PDF when trying to display the PDF
This method disables the \WPEL_Front::scan() method which was causes the problem.
Fixes #386
=> Resolve conflict with WP External Links plugin

src/helper/interface/Helper_Interface_Setup_TearDown.php, src/model/Model_Templates.php
Added an interface that template configurations can impliment so that a one-time
function gets executed when a PDF is installed through the GUI (setUp) and when
it gets deleted (tearDown).
Resolves #526
=> Template Configs can impliment setUp and TearDown methods

src/assets/css/gfpdf-styles.css
-  	Fix up image paths now assets are saved to the /dist/ directory
-  	Change the styles for common tags on Gravity PDF settings pages
=> CSS Changes

src/controller/Controller_Shortcodes.php, tests/phpunit/unit-tests/test-shortcodes.php
Sticky List taps into the `gform_confirmation` filter and manipulates the confirmation message. Unfortunately, in some cases it actually overrides the confirmation message entirely which means any filters like ours which run before it get overridden. 
Change out filter to run at "100" for `gform_confirmation`. Also did the same for `gform_notification` to pre-empt a similar conflict in future.
=> Fix GF Sticky List conflict with [gravitypdf] shortcode on confirmation page

src/templates/blank-slate.php, src/templates/focus-gravity.php, src/templates/rubix.php, src/templates/zadani.php, tests/phpunit/unit-tests/test-helper-templates.php
Added "Author URI" and "Tags" header options. Also enhanced the Description text and did a template version bump.
Resolves #542
=> Include support for new header info in core templates

src/helper/Helper_Field_Container.php, src/templates/blank-slate.php, src/templates/focus-gravity.php, src/templates/rubix.php, src/templates/zadani.php, tests/phpunit/unit-tests/test-field-container.php
By default Gravity Forms only supports single, two and three columns layouts. However, this four-column CSS code https://gist.github.com/WebEndevSnippets/5555354 has become prominent. With that in mind, we've added support for these custom class types.
=> Add four-column support in PDFs

src/assets/js/gfpdf-backbone.js, src/controller/Controller_Settings.php, src/helper/Helper_Migration.php, src/helper/Helper_Options_Fields.php, src/model/Model_PDF.php, src/model/Model_Settings.php, src/view/html/Settings/tools.php, tests/phpunit/unit-tests/test-pdf.php, tests/phpunit/unit-tests/test-settings.php
Mpdf only supports one type of OTF font file. From testing, it appears most fonts are the non-supported type. To prevent any confusion this change removes OTF fonts from being uploaded.
As a byproduct of this, issue #562 is fixed
=> Remove OTF fonts from being used

src/model/Model_Templates.php
On multisite installations I noticed the delete button wasn't showing up when a new PDF template is installed. I tracked the issue down to an incorrect path to the template file.
=> Correct the template path on installation

src/helper/Helper_Misc.php, src/model/Model_Actions.php, src/model/Model_Form_Settings.php, src/model/Model_Settings.php, src/model/Model_Templates.php
`wp_die()` was overriding the header response codes we were manually setting during AJAX calls. Remove all `header()` response codes and include them in `wp_die()` instead.
=> Set the response codes during wp_die()

src/assets/js/react/components/TemplateUploader.js
Instead of limiting uploads to a single zip file, users can upload multiple zip templates at the same time.
=> Allow multiple PDF templates to be uploaded at the same time

src/assets/js/react/router/templateRouter.js, src/helper/Helper_Data.php
Feedback showed "Activate" was an instant action. In fact, you pick the template and then need to "save". To account for this we have renamed Activate to Select.
Props to Adrian Gordon for the insight.
=> Change verbiage from Activate to Select

src/controller/Controller_Settings.php, tests/phpunit/unit-tests/test-settings.php
=> Resolve mime-issues with WordPress 4.7.1 by disabling check for TTF files

src/model/Model_Templates.php
Some users had issues uploading the zip files because they didn't have the fileinfo module enabled. We'll conditionally check for this and include the validation if it exists, otherwise don't do a mime check.
Resolves #581
=> Conditionally add mime validation to zip upload

src/assets/js/gfpdf-settings.js
This prevents issues when the PDF template is changed and the merge tag selector is used.
Fixes #567
=> Unbind the existing mergetag click event before setting them back up

src/helper/abstract/Helper_Abstract_Options.php
This prevents any PHP notices showing up when the capabilities array key doesn't exist
Fixes #586
=> Add isset and is_array check around $role['capabilities']

src/assets/js/react/components/ShowMessage.js, src/assets/js/react/components/TemplateList.js, src/assets/js/react/components/TemplateUploader.js, src/assets/js/react/router/templateRouter.js, src/helper/Helper_Data.php
This allows for better visibility when PDF templates are updated, as the existing templates don't move in the list automatically so it can be hard to see if anything happened.
=> Show generic PDF install /update message on PDF Template Dropzone

src/assets/js/react/components/TemplateButton.js
Tracked this problem down to Safari's document.activeElement not pointing to the correct dom node when the button was clicked. IE also showed the template manager when enter is pressed on non-ReactJS managed compenents.
I discovered browsers will treat the first `<button>` tag as the submit if the type isn't explicitly set to "button". Once done, I could remove the activeElement checks and fix the problem.
=> Fix issue with Advanced Template Manager opening in Safari

src/helper/Helper_PDF.php
wp_die() changes the headers we set to correctly display the PDF. While our version of Mpdf has exit right after the PDF generation already, if another plugin ships Mpdf it causes issues.
The way around this is to ensure we correctly exit right after the PDF is output to the browser.
=> Swap wp_die() to exit right after outputting PDF

src/controller/Controller_Activation.php, src/model/Model_Install.php, tests/phpunit/unit-tests/test-installer.php
User with index.php in the URL was having issues viewing the PDF. I mimicked the rewrite code from the WP-JSON API to resolve the problem.
This needs further hands on testing and unit testing before committing.
=> Fix rewrite rules issue with PDF

composer.json, gulpfile.js, package.json, src/assets/css/gfpdf-styles.css, src/assets/js/gfpdf-settings.js, src/bootstrap.php, src/controller/Controller_Settings.php, src/helper/Helper_Data.php, src/helper/Helper_Logger.php, src/helper/abstract/Helper_Abstract_Addon.php, src/helper/abstract/Helper_Abstract_Options.php, src/helper/interface/Helper_Interface_Extension_Settings.php, src/helper/licensing/EDD_SL_Plugin_Updater.php, src/model/Model_Settings.php, src/view/View_Settings.php, src/view/html/Settings/extensions.php, src/view/html/Settings/license.php, tests/phpunit/unit-tests/test-addon.php, tests/phpunit/unit-tests/test-ajax.php, tests/phpunit/unit-tests/test-bootstrap.php, tests/phpunit/unit-tests/test-logger.php, tests/phpunit/unit-tests/test-options-api.php, tests/phpunit/unit-tests/test-settings.php
Automatically handle license checks and include abstract class for common add-on functionality.
Changes include:
- Abstract the logger methods for use in add-ons and include unit tests
- Fix timezone offset issue with Monolog
- Add logging support to add-ons
- Add notice support for add-ons
- Added Global Extensions settings support
- Add automated license management
=> Add the add-on and licensing infrastructure

src/helper/fields/Field_Tos.php
If the user didn't "accept" the ToC we now include a cross in the document.
Fixes #580
=> Ensure the ToC Perk field is always shown in PDF

.travis.yml, README.txt, src/assets/js/gfpdf-settings.js
Add support for refractored mergetag JS code coming in Gravity Forms 2.3.
We've also ensured backwards compatibility with older versions of Gravity Forms too. When the minimum version requirement is bumped to 2.3+ we can remove that extra code.
See https://github.com/gravityforms/gravityforms/pull/58 for more details.
=> Merge Tag Initialisation Refractor

tests/mocha/unit-tests/components/template.activate.button.spec.js, tests/mocha/unit-tests/components/template.button.spec.js, tests/mocha/unit-tests/components/template.close.dialog.spec.js
=> Ensure no errors occur when using the JS History object during testing

src/helper/Helper_PDF.php
The recent change in how the master password is handled in Gravity PDF 4.2 causes the master password to be set to blank which causes issues in some PDF clients.
If the master password is blank, set to null so it's auto-generated by Mpdf.
Fixes #662
=> If master password is empty, set to `null`

src/controller/Controller_Install.php, src/model/Model_Install.php
This is in preparation for removing the Mpdf fonts from our distribution and prompting the user to install them separately.
Start for #184
=> Copy Mpdf fonts to our PDF Working Directory

src/bootstrap.php
This helps prevent any conflict with other plugins / themes
=> Restrict ReactJS entry point to Gravity PDF admin pages only

composer.json, src/bootstrap.php, src/controller/Controller_PDF.php, src/controller/Controller_Pdf_Queue.php, src/helper/Helper_Pdf_Queue.php, src/model/Model_PDF.php, src/statics/Queue_Callbacks.php, tests/phpunit/unit-tests/test-pdf-queue.php, tests/phpunit/unit-tests/test-pdf.php, tests/phpunit/unit-tests/test-slow-pdf-processes.php
This will stop the standard submission/resend notification functionality
and queue it up with the appropriate PDF generation.
Hooks are included to allow devs to add their own queue tasks.
Resolves #710
=> Add PDF/Email background processing on form submission and the resend notification feature.

src/assets/js/react/bootstrap/templateBootstrap.js
Ensure the correct default template is selected when we get the new select list and remove the change event trigger.
Resolves #651
=> Prevent multiple AJAX calls when template list changes (add/delete)

src/helper/fields/Field_Checkbox.php, src/helper/fields/Field_Html.php, src/helper/fields/Field_Post_Content.php, src/helper/fields/Field_Radio.php, src/helper/fields/Field_Section.php, src/helper/fields/Field_Textarea.php, src/helper/fields/Field_Tos.php, webpack.config.js
This prevents problems with using merge tags in attributes. Plus wp_kses_post() can better validate the markup as it's been transformed already.
Resolves #711
=> Pre-process any mergetags that go through wp_kses_post()

src/assets/css/gfpdf-styles.css
Fixes https://github.com/GravityPDF/gravity-pdf/issues/743
=> Override style change in WordPress 4.8 which caused display issues in the PDF Template Manager

src/view/View_PDF.php
This resolves a PHP notice and will allow the merge tag processing to work correctly.
=> Pass all the required fields to the preprocess_template_arguments() method

src/model/Model_PDF.php
Fallback to 'font' setting if no watermark font setting found
=> Add check for 'watermark_font' setting before using it.

src/model/Model_PDF.php, tests/phpunit/unit-tests/test-form-settings.php, tests/phpunit/unit-tests/test-helper-misc.php, tests/phpunit/unit-tests/test-helper-templates.php, tests/phpunit/unit-tests/test-options-api.php, tests/phpunit/unit-tests/test-pdf.php, tests/phpunit/unit-tests/test-settings.php, tests/phpunit/unit-tests/test-slow-pdf-processes.php
These notices were hidden because MPDF turned them off. We've since removed the PHP error reporting adjustment code.
=> Adjust tests to fix PHP notices

src/deprecated.php, src/helper/Helper_PDF.php
Also add new action that runs when the HTML sandbox is skipped and a getter function to return the current Mpdf object.
=> Add filter to allow the HTML sandbox to be skipped

composer.json
PHPUnit 7 made the phpunit6-compat.php file throw an error due to making PHPUnit\Util\Test a final class.
=> Restrict PHPunit to be less than v7

src/bootstrap.php, src/controller/Controller_PDF.php, src/controller/Controller_Pdf_Queue.php, src/helper/Helper_Options_Fields.php, src/model/Model_PDF.php, tests/phpunit/unit-tests/test-pdf.php, tests/phpunit/unit-tests/test-slow-pdf-processes.php
Give users the option to opt-in via a new PDF setting. This will stop a lot of issues related to Background tasks not firing correctly when there's a CURL problem triggering the background process.
=> Disable the background processing code by default

.babelrc, tests/mocha/arrow-function-coverage-fix.js, webpack.config.js
An issue with Istanbul and Babel7 code. Build issue was due to the `ModuleConcatenationPlugin` which is no longer needed since combining the vendor and app files together.
=> Resolve JS errors in build and tests

api.php, src/controller/Controller_PDF.php, src/deprecated.php, src/helper/Helper_Data.php, src/helper/Helper_PDF.php, src/model/Model_Install.php, src/model/Model_PDF.php, src/model/Model_Settings.php, tests/phpunit/unit-tests/test-installer.php, tests/phpunit/unit-tests/test-pdf.php
Also ensure the tmp location is cleaned up when fonts are deleted, removed unnecessary filters and update unit tests.
Resolves #819
Resolves #820
=> Define the mPDF tmp location and use that instead of the `template_fontdata_location`

src/model/Model_Install.php, src/model/Model_PDF.php, tests/phpunit/unit-tests/test-pdf.php
This prevents problems on some web hosting providers who cannot write to the PHP tmp directory
Resolves #836
=> Add fallback mPDF temporary directory when we cannot write PHP file to disk

composer.json, src/controller/Controller_PDF.php, src/controller/Controller_Shortcodes.php, src/helper/Helper_Sha256_Url_Signer.php, src/model/Model_PDF.php, src/model/Model_Shortcodes.php, tests/phpunit/unit-tests/test-pdf.php, tests/phpunit/unit-tests/test-shortcodes.php
Allow the shortcode to return the URL
Process shortcode in Redirect Confirmations differently to handle signed URLs
=> Allow signed URLs when using the Gravity PDF Shortcode

src/controller/Controller_PDF.php, src/model/Model_Install.php, src/model/Model_PDF.php
This resolves a growing conflict with third party plugins. Because WordPress will check for superglobals with matching names to the registered tags, it had unintended side effects (GravityView, MembersPress ect).
By only registering the tags on Gravity PDF endpoints, there will be no third party side effects.
As this change affects the core functionality of Gravity PDF (displaying PDFs in browser), verifying no unintended consequences occured is a must.
To test:
=> Conditionally register our rewrite tags on PDF endpoints

.gitattributes
This ensures `phpcs.xml` is excluded from the production build when running `./bin/build.sh`
=> Exclude `phpcs.xml` file from Git Archive command

src/helper/Helper_PDF.php
This allows developers to change any of the defaults we set in the `init()` method. 
TODO: write the documentation for this.
=> Add ability to access Mpdf object right after it's fully initialised

src/helper/Helper_Misc.php
Resolves #896 
*Steps to Replicate*
1. Start on the `development` branch of Gravity PDF
1. [Add a new PDF to any Gravity Form](https://gravitypdf.com/documentation/v5/user-setup-pdf/)
1. Select the Template tab and then locate the "Header" setting
1. Select the "HTML" tab in the Rich Text Editor and add the following:
```
<pagebreak>
<pagebreak/>
<pagebreak />
<pagebreak stuff="" other="">
<pagebreak stuff="" other=""/>
<div style="page-break-before:always"></div>
<div style="page-break-before: always"></div>
<div style="page-break-before: left"></div>
<div style="page-break-before:  left"></div>
<div style="page-break-before:right"></div>
<div style="page-break-after:always"></div>
<div style="page-break-after: avoid"></div>
<div style="page-break-after: left"></div>
<div …
```
=> Strip Page Breaks from Header / Footers

README.txt, pdf.php, src/controller/Controller_PDF.php, src/helper/Helper_Misc.php, src/helper/Helper_PDF.php, src/model/Model_Install.php, src/model/Model_PDF.php
Changes include:
* Housekeeping: Add filter `gfpdf_mpdf_post_init_class` to interact with mPDF right after the initial Gravity PDF object setup [GH#890]
* Bug: Fix URL rewrite issue with plugins that use `action` GET superglobal [GH#892]
* Bug: Fix conflict with the SG Optimizer plugin's Minify HTML option [GH#897]
* Bug: Strip Page Breaks from Headers and Footers to prevent Fatal PHP Error [GH#898]
=> 5.1.5 Release

.babelrc
Fixed Terminal WARNING: 'useBuiltIns' without declaring a core-js version
Resolves #904
Run: yarn build
=> Fixed WARNING: 'useBuiltIns' without declaring a core-js version

src/helper/fields/Field_Post_Category.php
Prevent string to array conversion by setting variables explicitly as arrays.
On a Local by Flywheel site with PHP7.2.
Create Gravity Form with a Category field type (under Posts) with the field type set to Checkboxes and save. Ensure you add a couple of post categories under Posts -> Categories. 
Submit a test entry and select one or two options from your category field. 
Add a new PDF to the form and select Zadani as the template type. Save.
View the PDF on the newly submitted entry. Prior to the patch a fatal error would occur. After the patch, it'll be correctly displayed.
=> Resolve PHP Fatal Error in PHP 7.2+

gulpfile.js, package.json, webpack.config.js, yarn.lock
Moving legacy Javascript from Gulp to Webpack bundler.
Run the following command:
- gulp
- yarn run build
=> Move legacy JavaScript from Gulp to Webpack

src/assets/js/gfpdf-settings.js
Issue: #920
Fixed gfpdf-settings.js legacy code 'not strict code' for causing error.
=> Fix gfpdf-settings.js legacy code 'not strict code' for causing error

src/Controller/Controller_Shortcodes.php, src/Exceptions/GravityPdfShortcodeEntryIdException.php, src/Exceptions/GravityPdfShortcodePdfConditionalLogicFailedException.php, src/Exceptions/GravityPdfShortcodePdfConfigNotFoundException.php, src/Exceptions/GravityPdfShortcodePdfInactiveException.php, src/Helper/Helper_Abstract_Pdf_Shortcode.php, src/Helper/Helper_Interface_Url_Signer.php, src/Model/Model_PDF.php, src/Model/Model_Shortcodes.php, src/bootstrap.php, src/helper/Helper_Url_Signer.php, tests/phpunit/unit-tests/test-pdf.php, tests/phpunit/unit-tests/test-shortcodes.php, tests/phpunit/unit-tests/test-slow-pdf-processes.php, tests/phpunit/unit-tests/test-url-signer.php
Refractor the Shortcode class to make it easier to reuse the code for other similar shortcodes
Checkout the branch and use the [gravitypdf] shortcode like normal. None of the features have changed, just the underlying code structure.
=> Refractoring the [gravitypdf] shortcode class 

src/Controller/Controller_PDF.php
Fixed #939
Users report PHP Generation Issue due to output already being sent
Need to be on Siteground host to replicate.
=> Drop Siteground Buffer instead of outputting it

.docker/docker-compose.yml, .docker/mu-plugins/gravitypdf.php, .docker/mu-plugins/src/Add_On_Bootstrap.php, .env.example, .gitattributes, .github/README.md, .gitignore, bin/env.sh, bin/functions.sh, bin/setup-docker.sh, bin/setup-gravitypdf.sh, bin/setup-local-env.sh, bin/setup-plugins.sh, bin/setup-wordpress.sh
Add build script to create Docker Test Site.
This will be eventually used for automated End To End Testing using TestCafe and Unit Testing. 
1. Start Docker. Note: if running Local By Flywheel, first run `docker-machine start`, then `docker-machine env` and run the command that gets spit out to configure your shell e.g `eval $(docker-machine env)`.
1. Copy `.env.example` to `.env` and replace `0000000000000000` with a valid Elite license key in `.env`
1. Run `./bin/setup-local-env.sh` from the command line
1. Access test site at `http://localhost:8888`, or the domain shown in the CLI if different. The username is `admin` and the password is `password`
=> Add scripts to build Docker Test Site

src/Controller/Controller_PDF.php, src/Helper/Helper_PDF.php
By moving the noindex call to the start of the URL endpoint process, we can ensure any errors also have a noindex and nofollow header set, instead of just successful PDF endpoints.
Resolves #955
Submit a form as a logged out user. Because you're in localhost, when you try view the PDF as the logged out user, you'll trigger an error.
Open your Browser Developer Tools and go to the Network tab. Reload the page with the PDF error and view the Response Headers. A new `X-Robots-Tag` will be present with `noindex` and `nofollow`.
=> Move noindex to beginning of PDF endpoint processing

composer.json, composer.lock
Resolves deprecation warning about uppercase characters in composer naming.
Also, update composer-managed plugins within confines of composer.json constraints.
Resolves #954
`composer install`
=> Fix querypath composer error

.travis.yml
Fixed Travis CI errors due to missing MySQL module.
See passing tests here: https://travis-ci.org/GravityPDF/gravity-pdf
=> Enable MySQL in Travis

src/Controller/Controller_PDF.php, src/Model/Model_PDF.php, tests/phpunit/unit-tests/test-pdf.php, tests/phpunit/unit-tests/test-slow-pdf-processes.php
Move the action so it runs only when the PDF is created and saved to disk. The PDF generation logic already includes the ability to only generate if the PDF doesn't already exist on disk (in the standard flow the PDF is cleaned up after the form submission process, so it's effectively run once).
Resolves #948
Configure a PDF on your form so that it will be automatically attached to a Notification. Also enable the "Always Save PDF" option.
Add the following filter to a MU Plugin or theme's `functions.php` file and add a breakpoint on the `$test = '';` line.
```
add_action( 'gfpdf_post_save_pdf', function( $pdf_path, $filename, $settings, $entry, $form ) {
$test = '';
}, 10, 5 );
```
Prior to the patch, Xdebug would stop on this line twice during form submission. After the patch, it only …
=> Ensure the gfpdf_post_save_pdf action isn't run twice

src/Model/Model_PDF.php
The codebase had a O(n2) loop, which was converted to an O(n) loop. Speeding up the PDF generation time.
Resolves #934
N/A
=> Remove recursive in_array call

src/Helper/Fields/Field_Post_Category.php
When a Category field contained a category with a comma included, everything after the first comma would be removed. This patch ensures the full string gets displayed.
Go to Posts -> Categories in your admin area, then add a new category title containing a comma. In your Gravity Form, add a Category field.
After submission with the comma-category option selected, view a Core PDF. Before the patch the category string would be truncated. Afterwards, it gets displayed correctly. 
You can also use the `?data=1` helper parameter to inspect the label / value we process.
=> Fix bug with displaying Categories with commas in the label/value

src/Helper/Helper_Abstract_Pdf_Shortcode.php, tests/phpunit/unit-tests/test-shortcodes.php
When the AJAX redirect was used, GF generated the redirect JS string and passed it to the filter we tapped into. Because it was a string, it was being handled by our text confirmation code. This patch corrects that problem.
1. Embed a form (any) on a WordPress Page or Post and enable AJAX mode
1. Ensure a PDF is configured on the form, then copy the [gravitypdf] shortcode show on the PDF List page
1. Open up the default Confirmation, select Redirect mode, then paste in the shortcode and save.
1. Submit the form embedded on your post/page, it'll hang and the browser Console will show a JS error
1. When checking out this branch, the AJAX Confirmation will work correctly. 
When testing, you should double check the non-AJAX redirect, page redirect, and text redirect also work as expected and …
=> Resolves an issue redirecting to the PDF in AJAX mode

src/Helper/Helper_PDF.php
Fix issue with setting the image DPI
=> Ensure IMG_DPI set during initialisation

src/View/html/Welcome/more.php, src/View/html/Welcome/welcome.php, src/assets/css/gfpdf-styles.css
Issue: #991 
This fix the issue above which is backwards compatible right up to WordPress 4.8.
=> Fixed Welcome Screen (backwards compatible right up to WordPress 4.8)

.gitignore, bin/json-payload.sh, package.json, src/Helper/Helper_Data.php, src/assets/js/react/api/coreFonts.js, src/assets/js/react/router/coreFontRouter.js
Instead of calling the GitHub API directly, during the plugin build process we will save the payload locally and then use it. This circumvent API restrictions by GitHub for unauthenticated users. 
Resolves #974
Run `yarn prebuild` to save the GitHub API JSON. Then use the Core Font Installer.
=> Download and load GitHub Core Font JSON Payload during build step

src/assets/css/gfpdf-styles.css, tests/mocha/unit-tests/react/components/Template/template.screenshot.spec.js, tests/mocha/unit-tests/react/components/Template/template.screenshots.spec.js
Resolve issue: #1010 
Adjusted CSS code to fix the Welcome Page logo view for small screen and fix up for JS unit test console warning.
Run:  yarn run test:js
=> Fixed Welcome Screen logo in small screen & console warnings

src/Helper/Fields/Field_Post_Category.php
Prevents error with Category checkbox fields when no value is passed.
Before PR
1. Add Category Checkbox field to Gravity Form
1. Configure Core template
1. Submit test entry
1 View PDF
1. Error will either show on screen (or when you download the PDF and open it up in a text editor the error will show up at the beginning of the file). If no error, double check `WP_DEBUG` set to `true` in `wp-config.php` file
After PR there will be no error.
=> Resolve PHP error when Category field is blank

src/Helper/Helper_Abstract_Pdf_Shortcode.php
Added a filter that checks the first parameter passed isn't a WP_Error
#999
=> Added a filter to check if the first parameter isn't a WP_Error

.travis.yml, package.json, src/bootstrap.php, tests/phpunit/unit-tests/test-form-settings.php, tests/phpunit/unit-tests/test-pdf.php
Correct issues with Gravity PDF when running unit tests under PHP7.4
=> Fix up unit tests for PHP7.4

src/Helper/Helper_Abstract_Pdf_Shortcode.php
Fixes 3rd party plugin issue 
Resolves #999
=>  Check for WP Errors on $form and $entry variables

bin/download-wordpress.sh, tests/e2e/page-model/helpers/page.js
Fix up E2E test suite. Only pull the latest WordPress production version.
yarn run test:e2e
yarn run test:e2e:headless
=> Fix up E2E test suite

src/Helper/Helper_PDF.php, src/deprecated.php
When loading images in the PDF which have a redirect, cURL will now follow that redirect automatically.
Include a image in the PDF which has a URL that 301 redirects. The image will now load correctly.
=> Set curl to follow redirects

src/Helper/Fields/Field_Consent.php
The label is set by an authenticated user, and is not defined by the public. We'll allow any HTML that passes wp_kses_post().
Add Consent field with HTML in label then view Core PDF
=> Allow HTML in Consent Label

src/Helper/Fields/Field_Quiz.php
=> Check variable exists before usage

phpcs.xml.dist, src/Statics/Queue_Callbacks.php
Add checks in case the form or entry could not be retrieved. It might have been deleted, or the database is just inaccessible.
1. Install Crontrol plugin
1. Enable Background Processing
1. Add breakpoint in Queue_Callbacks.php on line 68
1. Submit form with PDF attached to notification
1. When breakpoint triggered stop the running process
1. Delete entry
1. Go to Control plugin and run the gravitypdf queue item
1. Verify an Exception is thrown
=> Add additional error handling to queue Queue

api.php, src/Controller/Controller_Actions.php, src/Controller/Controller_Install.php, src/Controller/Controller_PDF.php, src/Controller/Controller_Pdf_Queue.php, src/Controller/Controller_Save_Core_Fonts.php, src/Controller/Controller_Settings.php, src/Helper/Helper_Abstract_Options.php, src/Helper/Helper_Abstract_Pdf_Shortcode.php, src/Helper/Helper_Migration.php, src/Helper/Helper_Misc.php, src/Helper/Helper_Pdf_Queue.php, src/Helper/Helper_Templates.php, src/Model/Model_Actions.php, src/Model/Model_Form_Settings.php, src/Model/Model_Install.php, src/Model/Model_Mergetags.php, src/Model/Model_PDF.php, src/Model/Model_Settings.php, src/Model/Model_Shortcodes.php, src/Model/Model_Templates.php, src/Statics/Queue_Callbacks.php, src/View/View_PDF.php, src/View/View_Settings.php, src/bootstrap.php
This ensures forward compatibility with Monolog v2 (even though we aren't doing a depedancy bump). 
Enable logging. Verify log file still written to.
=> Convert all log methods to PSR-3 standard

.travis.yml
Run the E2E tests under PHP7.4 to determine if there are any issues. 
If this passes, fixes https://github.com/GravityPDF/gravity-pdf/issues/986
You can also manually test PHP7.4 locally running Gravity PDF. No issues caused by Gravity PDF found.
=> Run E2E tests in PHP7.4

src/Helper/Helper_Data.php, src/assets/js/react/components/Template/TemplateList.js, tests/mocha/tests.bundle.js
Resolves an issue when the user did not have the `gravityforms_edit_settings` capability and tried to upload a template.
Resolves https://github.com/GravityPDF/gravity-pdf/issues/1039
Create a new role on the site and don't include the `gravityforms_edit_settings`  capability. Switch to this user and try upload a template.
=> Only show the template installer box if user has the privileges for it

src/Helper/Helper_Logger.php
Resolves a fatal error when using Monolog v2 with Gravity PDF, and you have your timezone offset setup.
Also corrected the log date and made it easier to read the log messages
- Bump Monolog composer constraints to v2 and do `composer update`
- Set timezone offset in WordPress Admin `Settings -> General`
- Enable Gravity Forms Logging
- Generate a PDF
- View Log file
=> Re-write the timezone logic to work correctly with Monolog v1 and v2

src/Helper/Fields/Field_Form.php, src/Helper/Fields/Field_Repeater.php, src/Helper/Helper_Field_Container.php, src/View/View_PDF.php
This PR makes the following changes:
- Set all `private` properties to `protected`
- Add new filter `gfpdf_field_container_class`
Refer to  https://github.com/GravityPDF/gravity-pdf/pull/1048 for the reason(s) why this change came about.
Devs who want to change how the `Helper_Field_Container` class works can now use the filter `gfpdf_field_container_class` to inject their own class (either an entirely new class, or one that extends the existing one and tweaks the functionality).
=> Allow Field_Container class to be more extensible

src/Model/Model_PDF.php, tests/phpunit/unit-tests/test-pdf.php
This resolve an issue when WordPress is running a subdirectory multisite, or it is installed in a subdirectory.
1. Fire up a Subdirectory multisite on your local machine
2. Create a signed PDF URL shortcode on the subsite
3. Submit the form
4. Try access the URL in an incognito browser window
=> Refine the URL builder for the signed PDF requests

src/Helper/Helper_Abstract_Pdf_Shortcode.php, tests/phpunit/unit-tests/test-shortcodes.php
=> Add type check to get_shortcode_information

src/Helper/Helper_PDF.php
When merge tags are processed, if they contained a special character < > & " ' then Gravity Forms would automatically encode it. To ensure the integrity of the password, we decode these settings before adding to mPDF.
Resolves #1058
1. Create form with Single Line Text field
2. Add Zadani PDF, enable security, and set the password to `{:1}`
3. Submit test entry and include special characters `< > & " '` in the field
4. View PDF and enter value entered into the field when prompted for the password
=> Decode special characters for the password and master password values

src/Controller/Controller_PDF.php, src/Model/Model_PDF.php
Resolves #985
Install Gravity Wiz and then the GP Populate Anything plugin. Use live merge tags `@{:1}` or `@{:1:fallback[value]}` in the form then view the PDF. No display issues will be present with these field types anymore.
=> Add support for GP Populate Anything's Live Merge Tags

src/Controller/Controller_Install.php, src/Controller/Controller_System_Report.php, src/Helper/Helper_Data.php, src/View/View_Settings.php, src/View/html/Settings/system_status.php, src/bootstrap.php, tests/phpunit/unit-tests/Controller/TestControllerSystemReport.php, tests/phpunit/unit-tests/View/TestViewSettings.php
Allow users to easily see if the `allow_url_fopen` setting is enabled or not on the web server. 
Resolves https://github.com/GravityPDF/gravity-pdf/issues/967
Go to Forms -> Settings -> PDF and navigate to the bottom
@jakejackson1 to refine text copy displayed to the user
=> Add allow_url_fopen status to System Status

src/Controller/Controller_Settings.php, src/assets/js/admin/settings/common/doUploadListener.js, tests/phpunit/unit-tests/test-settings.php
Prevents JS error about not allowing TTf fonts via the Media Library
Go to Font Installer and try upload a TTF font file via the media library
=> Re-register font mime type with WordPress so TTF fonts can be correctly uploaded

tests/phpunit/unit-tests/Model/TestModelPDFMetaBox.php, tests/phpunit/unit-tests/test-pdf.php
Moved the Metabox Unit Tests to each Test Files (Failure and Success).
Kindly run these following commands:
yarn test:php --filter=TestModelPDFMetaBox
Or PhpStorm's Unit test UI this class.
This is the spearhead of micro-test.
Screenshot updated.
Instruction updated.
=> Unit test pdf metabox 2.5

src/Controller/Controller_Upgrade_Routines.php, src/Deprecated/Vendor_Aliasing.php, src/autoload.php, src/bootstrap.php, tests/phpunit/unit-tests/Controller/Test_Controller_Upgrade_Routines.php, tests/phpunit/unit-tests/Deprecated/Test_Vendor_Aliasing.php, tests/phpunit/unit-tests/test-installer.php, tests/phpunit/unit-tests/test-query-path.php
Finalises the Vendor scoping feature.
`qp`, `htmlqp` and `html5qp` functions, and the `\Mpdf\Mpdf` class are available after the `init` hook is fired if you upgrade from a version prior to 6.0.
=> Add upgrade routine and enable vendor aliases for pre6.0 users only

src/assets/js/react/api/coreFonts.js
Regardless of the `Content-Type` header sent back when accessing the `/dist/payload/core-fonts.json` file, we should always parse a successful API request as JSON. 
Resolves #1069
1. Open the `.htaccess` file at the root of your WordPress directory and add `AddType none .json` to the top
2. In the `gf-2.5` branch if you run the Core Font Installer now you will get an error
3. If you checkout this branch and rerun the installer it will function as expected
4. If you remove the line added to `.htaccess` it will still function correctly
=> Always parse Core Font payload as JSON

src/Controller/Controller_Pdf_Queue.php, src/Controller/Controller_Upgrade_Routines.php, src/Helper/Helper_Pdf_Queue.php, src/Model/Model_PDF.php, src/bootstrap.php, tests/phpunit/unit-tests/Controller/Test_Controller_Upgrade_Routines.php, tests/phpunit/unit-tests/test-slow-pdf-processes.php
We changed the Background Process toggle from a Radio field to a Toggle. The Radio field had the values Enable and Disable, but the Toggle uses Yes and No. This update uses the new values and includes an upgrade routine from v5.
=> Swap Background Processing checks to new toggle Yes/No options

src/assets/scss/Component/_hidden.scss, src/assets/scss/gfpdf-styles.scss
Resolves #1128 
Load Global PDF Settings and notice the Custom Paper Size field doesn't flash on the screen before being hidden
=> Add hidden class

src/assets/js/admin/settings/common/setupDynamicTemplateFields.js, src/assets/js/react/bootstrap/fontManagerBootstrap.js, src/assets/js/react/bootstrap/templateBootstrap.js, src/assets/js/react/gfpdf-main.js, src/assets/scss/Component/_font-manager.scss, src/assets/scss/Component/_spinner.scss, src/assets/scss/Component/_template-manager.scss, src/assets/scss/MediaQueries/_min-1200.scss
Create a better experience for users by inlining the Advanced buttons for the Font and Template Managers.
Resolves #1124
1. View Global PDF Settings page
2. View Form PDF Settings page
3. View Tools tab (to check the Font Manager)
=> Inline the Font and Template Advanced buttons

api.php, tests/phpunit/unit-tests/test-api.php
This prevents a font being auto-installed multiple times when a template is reinstalled / upgraded.
Resolves #1151
1. Install template zip file that contains font
2. Check font has been installed
3. Reinstall same zip file
4. Check that installed font only appears once.
=> Only allow font to be installed via template if not already exists

src/assets/js/admin/settings/pdf/handleSecurityConditionals.js
Issue: #1173 
Toggle show/hide security password and privileges fields under 'Enable PDF Security'
=> Security JavaScript Toggle not showing/hidding PDF Settings

src/assets/js/react/components/FontManager/FontListItems.js, src/assets/scss/Component/_font-manager.scss, tests/js-unit/react/components/FontManager/FontListItems.test.js
=> Set valid HTML input field for font manager list

src/assets/js/react/gfpdf-main.js, src/assets/js/react/utilities/PdfSettings/addEditButton.js
Issue: #1152 
Add Add/Update button below open PDF Setting container automatically
=> Add Add/Update button below open PDF Setting container automatically

src/Helper/Helper_PDF.php, src/Model/Model_Form_Settings.php
Quick update on custom size data type.
Replace (int) with (float) on Helper_PDF.php and Model_Form_Settings.
Issue  : #1203 
1. Add a new PDF to a Form
2. Go to Appearance tab
3. Set the Paper Size to Custom and then the Custom value to 11.25 x 5.52 inches.
4. Save the PDF
5. View a generated PDF from an entry and check the paper size
FLOAT
INT
=> Update typecast from INT to FLOAT in custom paper size.

src/assets/js/react/components/FontManager/FontListItems.js, src/assets/scss/Component/FontManager/_font-manager.scss, tests/js-unit/react/components/FontManager/FontListItems.test.js
Issue: #1195 
To be able to tab through each font in the list and mark it as selected. Should also receive screenreader output on the radio field selector explaining what it is.
=> Fix font list radio button keyboard accessibility bug

src/assets/scss/Component/_gf-settings-containers.scss
Issues: #1189 #1190 
- Match GF style for legend
- Match GF page style for bold/label
=> Legend Styles on PDF pages don't match Gravity Forms styles

src/Model/Model_System_Report.php
Set default value on status page in which solves the problem with empty data on clipboard.
=> System status missing clipboard data and default values.

tests/e2e/tabs/tools/uninstall-gravity-pdf-field.test.js, tests/e2e/utilities/page-model/tabs/tools.js
Issue: Fix E2E test check for Gravity PDF uninstall option.
=> Adjust uninstall Gravity PDF E2E check

src/assets/js/react/components/FontManager/TemplateTooltip.js
Issue: With the new tooltip under font manager, font list column height needs to be automatically adjusted to avoid overlapping issue with update font column. (Screenshot attached)
**Step To Reproduce**
Steps to reproduce the behavior:
1. Go to Font Manager
2. Click/Open a font
3. Expand tooltip by clicking 'View template usage'
4. Click 'Cancel' button
=> Fix font manager 2 columns overlap issue

src/Model/Model_System_Report.php, src/View/View_System_Report.php, tests/phpunit/unit-tests/Controller/Test_Controller_System_Report.php
Create a method that checks for core template version number and compare it with the latest one (2.0.0), make sure that the export function still works as intended.
Added Model_System_Report.get_template_status(), utilize Helper_Templates ability to check for core template's header. I have able to compare the current version using php's version_compare method.
I have updated the View_System_Report as well, as I need to access the warning icon. Created a method for that and update a line which was that property is used.
Added html entities for cross icon on export.
#1221 
I still need the  correct instruction link for the core template update.
=> System Status : Add for core template version check.

src/Helper/Helper_Options_Fields.php
Since the introduction of toggle which replace the radio type. I noticed that we forgot to set the default value for Enable Logic.
Add default value for this field / std => 'Yes',  based on the field settings in v5.
#1255
=> Enable Conditional Logic settings by default.

src/Helper/Helper_Field_Container_Gf25.php
Force the last column in each row to have a 100% width so the rows can line up better.
Resolves #1258
=> Optimize column widths in PDFs

README.txt, pdf.php, src/Controller/Controller_Update_Dependency_Manager.php, src/View/View_Update_Dependency_Manager.php, src/View/html/UpdateDependencyManager/plugin_list_error.php, src/bootstrap.php, tests/phpunit/unit-tests/Controller/Test_Controller_Update_Dependency_Manager.php
This update will help alleviate problems with the 6.0 rollout by preventing sites being updated if they don't meet the minimum requirements. 
1. Install GF2.4
2. Go to Dashboard -> Updates and force an update check
3. Go to Plugins -> Installed Plugins page
4. See a notice about the 6.0 release being available, but requirements not me
5. Downgrade PHP or WordPress will do a similar thing
=> Prevent 6.0 update if dependancies not met, and show any v5 updates
